export { default as bike } from './bike.png';
export { default as bike2x } from './bike2x.png';
export { default as bike3x } from './bike3x.png';
export { default as dental } from './dental.png';
export { default as dental2x } from './dental2x.png';
export { default as dental3x } from './dental3x.png';
export { default as ehic } from './ehic.png';
export { default as ehic2x } from './ehic2x.png';
export { default as ehic3x } from './ehic3x.png';
export { default as expat } from './expat.png';
export { default as expat2x } from './expat2x.png';
export { default as expat3x } from './expat3x.png';
export { default as health } from './health.png';
export { default as health2x } from './health2x.png';
export { default as health3x } from './health3x.png';
export { default as household } from './household.png';
export { default as household2x } from './household2x.png';
export { default as household3x } from './household3x.png';
export { default as legal } from './legal.png';
export { default as legal2x } from './legal2x.png';
export { default as legal3x } from './legal3x.png';
export { default as liability } from './liability.png';
export { default as liability2x } from './liability2x.png';
export { default as liability3x } from './liability3x.png';
export { default as life } from './life.png';
export { default as life2x } from './life2x.png';
export { default as life3x } from './life3x.png';
export { default as privateHealth } from './private.png';
export { default as privateHealth2x } from './private2x.png';
export { default as privateHealth3x } from './private3x.png';
export { default as publicHealth } from './public.png';
export { default as publicHealth2x } from './public2x.png';
export { default as publicHealth3x } from './public3x.png';
export { default as disability } from './disability.png'
export { default as disability2x } from './disability2x.png'
export { default as disability3x } from './disability3x.png'
export { default as itliability } from './itliability.png'
export { default as itliability2x } from './itliability2x.png'
export { default as itliability3x } from './itliability3x.png'