export const blockedDogBreeds = [
  'American Pit Bull Terrier',
  'American Straffordshire Terrier',
  'Bullmastiff',
  'Bullterrier (any kind)',
  'Dogo Argentino',
  'Dogue de Bordeaux',
  'Fila Brasileiro',
  'Mastiff',
  'Mastín Español',
  'Mastino Napoletano',
  'Pit Bull Terrier',
  'Rottweiler',
  'Staffordshire Bullterrier',
  'Tosa Inu',
];
