export const breeds = [
  'Afghan',
  'Aidi',
  'Akita Inu',
  'Alano',
  'Alaskan Malamute',
  'American bandogg mastiff',
  'Anglo Francais de Petite Venerie',
  'Aregeois',
  'Australian Cattle Dog',
  'Australian Kelpie',
  'Australian Shepherd',
  'Azawakh',
  'Bandog',
  'Barbet',
  'Karelian bear dog',
  'Barzoi',
  'Baseji',
  'Basset Artesien-Normand',
  'Basset Bleu de Gascogne',
  'Basset D Artois',
  'Basset Fauve de Bretagne',
  'beagle',
  'Beagle Harrier',
  'Beauceron',
  'Bergamasker',
  'Berger de Brie',
  'Berger des Pyrenees',
  'Berger Picard',
  'Bernard',
  'Bichon a Poil Frise',
  'Bichon Havanais',
  'Billy',
  'Blood dog',
  'Bobtail',
  'Bohemian rough beard',
  'Bolognese',
  'Bouvier of the Flandre',
  'Boxer',
  'Bracco Italiano',
  'Alpine Dachsbracke',
  'Balkan bracket',
  'Brandlbracke',
  'German Hound',
  'Finnish Hound',
  'Hygen Hound',
  'Yugoslav three -colored',
  'Short -haired Istrian Bracke',
  'Polish bracket',
  'Shrine -haired Istrian Bracke',
  'Sauerland Dachsbracke',
  'Savetal Bracke',
  'Swedish Dachsbracke',
  'Transylvanian Bracke',
  'Slovak Black Bild Bracket',
  'Hochgebirgsbracke',
  'Tyrolean Hound',
  'Westphalian Dachshund',
  "Braque d'uerverne",
  "Braque de l'Ariège",
  'Braque du bourbonnais',
  'Braque dupuy',
  'Braque francais',
  'Braque Saint-Germain',
  'Briard',
  'Brawolmer',
  'Bruno du law',
  'Norwegian Buhund',
  'American Bulldog',
  'Bulldog',
  'Azores bulldog',
  'English bulldog',
  'French bulldog',
  'Bullmastiff',
  'Ca de Bestiar',
  'Ca de Bou',
  'Cane Corso',
  'Cane da Pastore',
  'Cao da Serra da Estrela',
  'Cao da Serra de Aires',
  'Cao de Agua Portugues',
  'Cao de Castro Laboreiro',
  'Cesky Fousek',
  'Chien de Berger de Beauce',
  'Chien de Saint Hubert',
  'Chihuahua',
  'Chincha Bull',
  'Chinese Crested Dog',
  'Chinese wrinkle dog',
  'Chinese hairless skip dog',
  'Chow-Chow',
  'Coban Köpegi',
  'Bearded Collie',
  'Border Collie',
  'collie',
  'Coton de Tulear',
  'Roof dog',
  'dachshund',
  'Dalmatian',
  'German wire hair',
  'German short hair',
  'German long hair',
  'German stubborn hair',
  'German boxer',
  'German quail dog',
  'Do Khyi',
  'Doberman',
  'Bordeaux mast',
  'Downhound',
  'Brazilian mastiff',
  'Danish mastiff',
  'German Mastiff',
  'English mastiff',
  'Italian mastiff',
  'Spanish mastiff',
  'Tibet Dogge',
  'Dogo Argentino',
  'Dogo Canario',
  'Dogo Mallorquin',
  'Drentsche Patjshond',
  'Drever',
  'Dunker',
  'Swedish moose dog',
  'Norwegian moose dog',
  'English pointer',
  'Epagnule Bleu de Picardie',
  'EPAGENUL Breton',
  'EPAGENUL de Pont Audemer',
  'EPAGENUL Francais',
  'EPAGENUL Nain Continental',
  'EPAGENUL PICARD',
  'Erdelyi Kopo',
  'Eurasian',
  'Fila Brasileiro',
  'Finsk Spets',
  'Finsk Stövare',
  'American Foxhound',
  'Foxhound',
  'Francais Blanc et Noir',
  'Francais Blanc et Orange',
  'Francais tricolor',
  'Galgo Espanol',
  'Gammel dansk hønsehund',
  'Mountain Jugoslav',
  'Balkanski Gonic',
  'IStarski Ostrodlaki Gonic',
  'Jugoslavenski Planinski Gonic',
  'Jugoslavenski Trobojni Gonic',
  'Grand Anglo Francais',
  'Grand Bleu de Gascogne',
  'Grand Gascon Saintongeois',
  'Greyhound',
  'Greek detection dog',
  'Belgian grip',
  'Briquet Griffon Vendenen',
  'Brussels Griffon',
  'Grand Basset Griffon Vendenen',
  'Grand Griffon Vendenen',
  'Griffon a Poil Laineux',
  'Griffon Belge',
  'Griffon Bruxellois',
  'Griffon d arret à poil major',
  'Griffon Fauve de Bretagne',
  'Griffon Nivernais',
  'Korthals Griffon',
  'Petit Basset Griffon Vendenen',
  'Groenendael',
  'Greenlandhund',
  'Haldenstoever',
  'Hamilton Stövare',
  'Harrier',
  'Havanese',
  'Heath',
  'Hellenikos ichnilatis',
  'Anatolian shepherd dog',
  'Hokkaido',
  'Dutch rattler',
  'Hollandse Smoushond',
  'Basset Hound',
  'Black and Tan Coonhound',
  'Bloodhound',
  'Irish Wolfhound',
  'Norwegian Hound',
  'Otterhound',
  'Pharaoh Hound',
  'Saarloos Wolfhound',
  'Hovawart',
  'Hrvatski Ovcar',
  'Old Dine chicken dog',
  'Burgos chicken dog',
  'Portuguese chicken dog',
  'Husky',
  'Hygenhund',
  'Iceland dog',
  'Italian wind chime',
  'Jämthund',
  'Jämtländer',
  'Japan Chin',
  'Kai Inu',
  'Kanaan dog',
  'Kangal',
  'Kelb Tal Fenek',
  'Kishu Inu',
  'Small Brabant',
  'Small Münsterländer',
  'Comondor',
  'Kuvasz',
  'Laekenois',
  'Lagotto',
  'Landseer',
  'Lapin -poroira',
  'Finnish Lapphund',
  'Swedish Lapphund',
  'Svensk Lapphund',
  'Lapplatske Spets',
  'Lappland reindeer dog',
  'Balearic drives',
  'Bernese drive',
  'Italian drive dog',
  'Lucerne drive dog',
  'Swiss drive dog',
  'Schwyzer drive dog',
  'Leonberger',
  'Lhasa apso',
  'Loan',
  'Norwegian Lundehund',
  'Magyar Agar',
  'Magyar Vizsla',
  'Malinois',
  'Maltese',
  'Mastiff',
  'Mastin de los pirineos',
  'Mastine Espanol',
  'Mastino Napoletano',
  'Molosser',
  'pug',
  'Mudi',
  'Mexican naked',
  'Peruvian naked',
  'Napoletano',
  'Newfoundland',
  'Dutch kooikerhondje',
  'Nihon Supittsu',
  'Nihon teria',
  'Norbotten Spets',
  'Otterhund',
  'Owscharka',
  'Beijing palace dog',
  'Papillon',
  'Pekinese',
  'Perdigueiro Portugues',
  'Perdiguere de Burgos',
  'Perro de Agua Espanol',
  'Perro de Pastor Catalan',
  'Perro de Presa Canario',
  'Perro de Presa Mallorquin',
  'Perro Sin Pelo del Peru',
  'Petit Bleu de Gascogne',
  'Petit Brancon',
  'Petit Chien Lion',
  'Petit Gascon Saintongeois',
  'Phalene',
  'Pharaoh dog',
  'Picard',
  'Affenpinscher',
  'German Pinscher',
  'Austrian Pinscher',
  'Dwarf',
  'Pit bull',
  'Podenco Canario',
  'Podenco ibicenco',
  'Podengo Portugues',
  'Podhalan',
  'Poitevin',
  'Polish lowlands dog',
  'Polski Owczarek Nizinny',
  'Polski owczarek podhalanski',
  'Porcelaine',
  'Dutch sheep sp fored',
  'poodle',
  'Poodle pointer',
  'Puli',
  'Pumi',
  'Pyrenäenenberghund',
  'Pyrenea dog',
  'Rafeiro do Alentejo',
  'Vineyard dog',
  'Chesapeake Bay Retriever',
  'Curly Coated Retriever',
  'Flat Coated Retriever',
  'Golden retriever',
  'Labrador',
  'Nova Scotia Duck Tolling',
  'Rhodesian Ridback',
  'Rottweiler',
  'Russian-European Laika',
  'Sabueso Espanol',
  'Saluki',
  'Samojede',
  'Sankt-Bernhards dog',
  'Sarplaninac',
  'AC Weisser Shepherd',
  'Belgian German Shepherd',
  'German shepherd dog',
  'Dutch German Shepherd',
  'Illyrian Shepherd',
  'Karst Shepherd',
  'Catalonic German Shepherd',
  'Croatian German Shepherd',
  'Maremmememen-Abruzzze',
  'Pyrenees Shepherd (shorthair)',
  'Pyrenees Shepherd (long hair)',
  'Shepherd',
  'White shepherd',
  'Schapendoes',
  'Schillerstövare',
  'Giant',
  'schnauzer',
  'Dwarf snout',
  'Segugio Italiano',
  'Appenzell Mountain dog',
  'Bernese Mountain Dog',
  'Entlebuch Sennenhund',
  'Swiss',
  'English Setter',
  'Gordon Setter',
  'Irish red and white setting',
  'Irish Red and White Setter',
  'Irish setter',
  'Shar-Pei',
  'Old English Sheepdog',
  'Shetland Sheepdog',
  'Sheltie',
  'Shiba Inu',
  'Shih Tzu',
  'Shikoku Inu',
  'Siberian Husky',
  'Sloughi',
  'Cuvac Slovensky',
  'Hruborsty Stavac Slovensky',
  'Kopov Slovensky',
  'Slovakian Tchuwatsch',
  'Smalandstövare',
  'American Cocker Spaniel',
  'American Water Spaniel',
  'American water paniel',
  'Cavalier King Charles Spaniel',
  'Clumber Spaniel',
  'Cocker spaniel',
  'English cocker Spaniel',
  'English jumper Spaniel',
  'Field Spaniel',
  'Irish water paniel',
  'Irish Water Spaniel',
  'King Charles Spaniel',
  'Sussex Spaniel',
  'Tibeti Spaniel',
  'Welsh Springer Spaniel',
  'Spanish Mastiff',
  'Spinone Italiano',
  'German point',
  'Finnenspitz',
  'Japan-Spitz',
  'Norbottenpitz',
  'Swedish Schäferspitz',
  'Pointed',
  'Stabijhoun',
  'South Russian Owscharka',
  'Suomenajokoira',
  'Suomenlapinkoira',
  'Suomenpystykorva',
  'Tapahund',
  'Teckel',
  'Airedale Terrier',
  'American Pit Bull Terrier',
  'American Stafford Terrier',
  'American Staffordshire Terrier',
  'Australian Silky Terrier',
  'Australian Terrier',
  'Bedding Terrier',
  'Border Terrier',
  'Bull terrier',
  'Cairn Terrier',
  'Cesky Terrier',
  'Dandie Dinmont Terrier',
  'German hunting terrier',
  'English Toy Terrier',
  'Fox Terrier',
  'Glen of Imaal Terrier',
  'Irish Terrier',
  'Jack Russell Terrier',
  'Japanese terrier',
  'Kerry Blue Terrier',
  'Lakeland Terrier',
  'Manchester Terrier',
  'Norfolk Terrier',
  'Norwich Terrier',
  'Parson Jack Russell Terrier',
  'Pit bull terrier',
  'Black Russian Terrier',
  'Black terrier',
  'Scottish Terrier',
  'Sealyham Terrier',
  'Skye Terrier',
  'Soft-Coated Wheate Terrier',
  'Staffordshire bull terrier',
  'Tibet terrier',
  'Welsh Terrier',
  'West Highland White Terrier',
  'Yorkshire Terrier',
  'Tervueren',
  'Tibet Mastiff',
  'Great',
  'Tosa Inu',
  'Vallhund',
  'VestgötaSpets',
  'Volpino Italiano',
  'German prime dog (wire hair)',
  'German pretense dog (short hair)',
  'German prime dog (long hair)',
  'German prime dog (stitch -haired)',
  'Great Münsterländer',
  'Italian pointing dog',
  'Slovakian into the hunde (wire hair)',
  'Roller',
  'Portuguese water dog',
  'Spanish water dog',
  'Weimaran',
  'Welsh Corgi Cardigan',
  'Welsh Corgi Pembroke',
  'West Siberian Laika',
  'Weather hoop',
  'Whippet',
  'Afghan greyhound',
  'Arabic greyhound',
  'Russian greyhound',
  'Spanish greyhound',
  'Hungarian greyhound',
  'Irish wolfhound',
  'Agassin',
  'Akbasch',
  'Alangu Mastiff',
  'Alapaha Blue Blood Bulldog',
  'Old Dan',
  'Old German herding dog',
  'Fuchs (old German herding dog)',
  'Yellow cheek (old German herding dog)',
  'Harzer Fuchs (old German herding dog)',
  'Cow dog (old German herding dog)',
  'Schaf poodle (old German herding dog)',
  'Black (old German herding dog)',
  'Old German herding dog (Strobel)',
  'Tiger (old German herding dog)',
  'Ardennes dribble dog',
  'Armant',
  'Australian Stumpy Tail Cattle Dog',
  'Australia Heeler',
  'Bakarwal',
  'Bangkaew Dog',
  'Barak',
  'Bardino',
  'Germanic bear dog',
  'Basque ratero',
  'Bavarian mountain welding dog',
  'Berger Blanc Suisse',
  'Berger de Laeken',
  'Berger de Savoie (Berger des Alpes)',
  'Berger du Languedoc',
  'Berne Laufhuind',
  'Bisben (Himalaja Schäferhund)',
  'Blenheim',
  'Blue Lacy',
  'Boerboel',
  'Bolonka Franzuska',
  'Bolonka Zwetna',
  'Italian bracket',
  'Celtic bracket',
  'Black -fashion bracket',
  'Sicilian bracket',
  'Steinbracke',
  'Styrian bracket',
  'Hungarian bracket',
  'Brazilian mastiff',
  'Rater Mallorqui',
  'Cane da Pastore Maremmano Abruzzese',
  'Cao Fila de Sao Miguel',
  'Carolina dog',
  'Carpatin',
  'Catahoula Bulldogge',
  'Catahoula Leopard dog',
  'Chambray',
  'Chien de Montagne des Pyrénées',
  'Chien de Trait Belge',
  "Chien d'Artois",
  'Chin',
  'Chinese Chongqing dog',
  'Chinoook',
  'Chippiparai',
  'Choden dog',
  'Chortaj (Hortaya Borzay)',
  'Cimarrón Uruguayo',
  'Cirneco dell’etna',
  'Cocker Poo',
  'American Collie',
  'Combai',
  'Continental Bulldog',
  'Coonhound',
  'Corgi',
  'Cursinu',
  'Da Capo Dog',
  'Dwarf dack',
  'Dansk-Svensk Gårdshund',
  'Designer dog',
  'dingo',
  'Argentine mastiff',
  'Canarian mastiff',
  'Elo',
  'English Shepherd',
  'Epagnule de Saint-Uusuge',
  'Estrela mountain dog',
  'European sled dog',
  'English foxhound',
  'French base dog',
  'Frisian water dog',
  'Gråhog',
  'Big poodle',
  'Hallstrom dog',
  'Hannoverian welding dog',
  'Hawaiian Poi Dog',
  'Karakatsch Bulgarian shepherd dog',
  "Maremman's shepherd dog",
  'Romanian shepherd dog',
  'Bluetick Coonhound',
  'Caravan Hound',
  'English Coonhound',
  'Mudhol Hound',
  'Plott Coonhound',
  'Rampur Hound',
  'Redbone Coonhound',
  'Redtick Coonhound',
  'Scandinavian Hound',
  'Treing Walker Coonhound',
  'Hubertus dog',
  'Huntaway',
  'New Zealander Huntaway',
  'Alaska Husky',
  'Hybrid dog',
  'Irish Red Setter',
  'Italian wolf dog',
  'Jonangi',
  'Kaikadi',
  'Karelo-Finnish Laika',
  'Kafkas (kars dog)',
  'Kashmir Mastiff',
  'Caucasian owscharka',
  'Keeshond',
  'Kelpie',
  'Kerry Beagle',
  'Kintamani dog (Bali-Mountain Dog)',
  'Kooikerhondje',
  'Kopov',
  'Korea Jindo Dog',
  'Kromfohrländer',
  'Kyi Leo',
  'Labradoodle',
  'Lacy Dog',
  'Laika',
  'Laika Jacutic',
  'Laika Eastern Siberian',
  'Laika Russian-European',
  'Lancashire Heeler',
  'Bosnian',
  'French drive',
  'Jura drive dog',
  'Montenegrin Montalen',
  'Polish drive dog',
  'Transylvanic drive dog',
  'Laverack Setter',
  'Longdog',
  'Louisiana Catahoula Leopard Dog',
  'Ambush',
  'Maneto',
  'Markiesje',
  'Mâtin',
  'Mcnab',
  'Mikawa Inu',
  'Miniature Australian Shepherd',
  'Mioritic',
  'Central Asian Tazi',
  'Moscow watchdog',
  'Mucuchies',
  'Münsterländer',
  'Inca-Nackthund',
  'Nederlandse Herdershond',
  'Norwegian moose dog gray',
  'Norwegian moose dog black',
  'Ogar Polski',
  'Ohar',
  'Pachon Navarro',
  'Pai',
  'Paleiyakaran',
  'Pariah round',
  'Pastor Garafiano',
  'Pastor Vasco Euskal Artzain Txakurra',
  'Perro de Ganado Majorero',
  'Perro Majorero',
  'Harlekinpin',
  'Deer',
  'Podenco Andaluz',
  'Podenco Andaluz Maneto',
  'Podenco Enano',
  'Podenco Malgueno',
  'pointer',
  'Prague Rattler',
  'Prazsky Krysarik',
  'Small poodle',
  'Royal spuge',
  'Sheep poodle',
  'Dwarf poodle',
  'Pug',
  'Pulp',
  'Rajapalayam',
  'Rastreador Brasileiro',
  'Ratonero Bodeguero Andaluz',
  'Ratonero Mallorquín',
  'Ratonero Valenciano',
  'Roman battle dog',
  'Ruby',
  'Russkiy Toy',
  'Saarloos Wolfhund',
  'Sanshu',
  'Sapsali',
  'Belgian Shepherd Malinois',
  'Belgian German Shepherd Tervueren',
  'Canadian Shepherd',
  'Eastern European Shepherd',
  'Portuguese German Shepherd',
  'Romanian shepherd',
  'Scottish shepherd',
  'Hungarian shepherd',
  'Central Asian Shepherd',
  'Belgian Shepherd Groenandael',
  'Belgian Shepherd Laekenois',
  'Slensi dogs',
  'Sailing',
  'Medium -sized',
  'Segusian',
  'Siegerländer cowhound',
  'Silken Windsprite',
  'Boykin Spaniel',
  'French Spaniel',
  'Continental dwarf spaniel',
  'Norfolk Spaniel',
  'Großpitz',
  'Dutch point',
  'Italian small spitz',
  'Small tip',
  'Medium -spitz',
  'Wolfspitz',
  'Dwarf',
  'St. Bernhards dog',
  'Taigan',
  'Taiwanhund',
  'Tamascan',
  'Telomian',
  'Ténériffs',
  'Teepezeuzeuimtli',
  'American Hairless Terrier',
  'American Toy Terrier',
  'Biewer Terrier',
  'Biewer Yorkshireterrier',
  'Boston Terrier',
  'Brazilian terrier',
  'English Bull Terrier',
  'Patterdale Terrier',
  'Council Terrier',
  'Silky Terrier',
  'Tchiorny Terrier',
  'Dwarf Bull Terrier',
  'Tesem',
  'Texas Blue Lacy',
  'Thai Bangkaew Dog',
  'Thai Ridback',
  'Peat dog',
  'Tornjak',
  'Treing Tennessee Brindle',
  'Turnpit Dog',
  'Hungarian occasion',
  'Original dog',
  'Urban',
  'Verdino',
  'Villano de Las Encartaciones',
  'Villanuco de Las Encartaciones',
  'Vizla',
  'quail',
  'Welsh Sheepdog',
  'Westerwald cowhound',
  'Greyhound',
  'Barsoi',
  'Berber wind dog',
  'Chart Polski',
  'Deerhound',
  'Silken greyhound',
  'Tuareg wind dog',
  'Wind chime',
  'Czechoslovakian Wolfhund',
  'Xoloitzcuintle',
  'Miniature Bull Terrier',
  'Berger de Beauce',
  'Goran dog',
  'Karabas',
  'Kraski Ovcar',
  'Liptak',
  'Central Asian Owscharka',
  'Slovensky Cuvac',
  'American Akita',
  'Great Swiss Sennen Dog',
  'American Bully',
  'Old English Bulldog',
  'Short -haired',
  'Afghan Hound',
  'Balutschi wind dog',
  'Atlas Mountain Dog',
  'Aiidi',
  'Ayidi',
  "Chien de l'Tlas",
  'Atlas Sheepdog',
  'Waterside Terrier',
  'Bingley Terrier',
  'Akbas',
  'Akita Ken',
  'Japanese Akita',
  'Akita-Inu',
  'Bully Kutta',
  'Alano Espanol',
  'Otto',
  'Alpine Erzgebirgler Dachsbracke',
  'Austrian Dachsbracke',
  'Great Japanese Dog',
  'Great Japanese dog',
  'American bulldog',
  'Old Country Bulldog',
  'Old English White',
  'American nude and',
  'Pit Bull',
  'Apbt',
  'Amstaff',
  'Toy Fox Terrier',
  "Chien d'Eau Américain",
  'Perro de Agua Americano',
  'American Foxhound',
  'Appenzellerhund',
  'Appezöller Bläs',
  'Bouvier des Ardennes',
  'Australian driving dog',
  'Blue Heeler',
  "Hall's Heeler",
  'Queensland Heeler',
  'Australian Shepherd',
  'Australian Sheepdog',
  'Barb',
  'Sydney Silky',
  'Australian Silky',
  'Bakharwal Mastiff',
  'Gujjar Watchdog',
  'Kashmiri Bakharwal Dog',
  'Srpski Gonic',
  'Ilirski Gonic',
  'Illyrian',
  'French water dog',
  'Barzaia',
  'Russian wolfhound',
  'Borzoi',
  'Congo terrier',
  'Blue basset of the Gascogne',
  'Basset',
  'Highland Collie',
  'Mountain Collie',
  'Hairy Mou Ed Collie',
  'BAS-ROUGE',
  'Rothbury Terrier',
  'Chien de Berger Belge',
  'Berger de Bergame',
  'Cane da Pastore Bergamasco',
  'Bergamasco Shepherd Dog',
  'Perro de Pastor Bergamasco',
  'Berger des cevennes',
  'Berger de la Crau',
  'Berger de Picardie',
  'Dürrbächler',
  'Bouvier Bernois',
  'Bernese Mountain Dog',
  'Perro Boyero de Montana Bernes',
  'Chien du Saint-Bernard',
  'Saint Bernard Dog',
  'Perro San Bernardo',
  'Curved bichon',
  'Biewer Yorkshire a la Pom-Pon',
  'Himalayan Bisben Sheepdog',
  'Black-red raccoon dog',
  'Lacy Game Dog',
  'Lacy Hog Dog',
  'Elder English Shepherd',
  'Franzuskaya Bolonka',
  'Tsvetnaya Bolonka',
  'Dogue de Bordeaux',
  'Bordeaux Mastiff',
  'Flandrian driving dog',
  'Carinthian bracket',
  'Arege-headed dog',
  'Bourbonnaiser',
  'Braque Charles',
  'Braque compiegne',
  'Terrier Brasileiro',
  'Perro de Pastor Mallorquín',
  'Mallorca head dog',
  'Mallorca matters',
  'Mallorca Mastiff',
  'Perro Dogo Mallorquin',
  'Cane Corso Italiano',
  'Italian Corso dog',
  'Corso dog',
  'Cane di Maccelaio',
  'American dingo',
  'Dixie dingo',
  'North American Native Dog',
  "Indian's Dog",
  'Yellow Dog',
  'Yaller Dog',
  'Ciobanesc Romanesc Carpatin',
  'Zavod',
  'Czech terrier',
  'Polish greyhound',
  'Artois Hound',
  'Techichi',
  'Chihuahueño',
  'Chinese Chongqing Dog',
  'Thanjavur dog',
  'Chodsky pes',
  'Choden countries dog',
  'Chortaja Borzaja',
  'Hortaya Borzaya',
  'Hoard',
  'Horty',
  'Perro Criollo',
  'Perro Gaucho',
  'Cocker poo',
  'Cockapoo',
  'Indian Beardog',
  'Chien Corse',
  'Shorthair Dachshund',
  'Long -haired dachshund',
  'Radhaar Dachshund',
  'Dalmatinac',
  'Sällkapshund',
  'Danish-Swedish farm dog',
  'Scottish Deerhound',
  'Highland Deerhound',
  'Scottish deer dog',
  'Westfälische Bracke',
  'Olper Bracke',
  'Sauerländer Bracke',
  'Ulm mastiff',
  'Hatzrüde',
  'Saupacker',
  'Big mastiff',
  'Old German Shepherd',
  'Pomeranian',
  'German quail',
  'Dobermanpinscher',
  'Argentine Mastiff',
  'Canary Dog',
  'Dunkerbracke',
  'Dunkerlaufhund',
  'American English Coonhound',
  'Brittany',
  'Bretonian',
  'Pont-Audemer-Spaniel',
  'Picardie spaniel',
  'EuroHound',
  'Finnish pointed',
  'Lapinkoira',
  'French white and black drive dog',
  'French white-orange drive dog',
  'French three -color drive dog',
  'Bouledogue Francais',
  'Irish Glen of Imaal Terrier',
  'Big Basset Griffon Vendéen',
  'Big Blue Gascogner Drive Dog',
  'Great English greyhound',
  'Grand Griffon Nivernais',
  'Chien de Pays',
  'Haldenstövare',
  'Haldstover',
  'Haldenbracke',
  'Hald run',
  'Halden-Stövare',
  'New Guinea thing',
  'Hamiltonstövare',
  'Hamilton Run dog',
  'Hamilton Bracke',
  'Bichon Habanero',
  'Greek drive dog',
  'Greek bracke',
  'Hokkaido dog',
  'Ainu dog',
  'Ainu Inu',
  'Hokkaido-Ken',
  'Hollandse Herdershond',
  'Herder',
  'Slovakian rough beard',
  'Hygenlauf dog',
  'Irish red and white setting',
  'Icelandic point',
  'Icelandic German Shepherd',
  'Lupo Italiano',
  'Italian Greyhound',
  'Piccolo Levriero Italiano',
  'Nippon terrier',
  'Nishon terrier',
  'Japanese point',
  'Three -colored Serbian drive dog',
  'Inu',
  'Tora Inu',
  'Kai Tora-Ken',
  'Israel Spitz',
  'Canaan Dog',
  'Carabash',
  'Bulgarian German Shepherd',
  'Karjalankarhukoira',
  'Björnhund',
  'Karst dog',
  'GOS d’Artura Catala',
  'Chewing',
  'Caucasian Owscharka',
  'Caucasian Shepherd',
  'Kawkasky Owscharka',
  'Kavkazkaia Ovtcharka',
  'Pocadan',
  'Blue Irish terrier',
  'English toy Spaniel',
  'Anjing Kintamani Bali',
  'Kishu-Ken',
  'Hungarian shepherd dog',
  'Butterfly dogs',
  'Slovakian drive',
  'Jindo-Kae',
  'Jindo-Kyon',
  'Griffon a Poil Dur',
  'IStarski Kratkodlaki Gonic',
  'Kuvacs',
  'Lagotto Romagnolo',
  'Romagna water dog',
  'Ormskirk Heeler',
  'Finnish Laplandhirten dog',
  'Lhasatersrier',
  'Lion dog',
  'Catahoula Cur',
  'Maremmaner Mountain Dog',
  'Hollandse Tulphond',
  'Old English Mastiff',
  'Mastín del Pirineo',
  'Pyrenees-Mastiff',
  'Spanish mastiff',
  'Mastin Leonés',
  'Mastine Extremeo',
  'Mastin Manchego',
  'Neapolitan Mastiff',
  'Miniature American Shepherd',
  'Mini bull terrier',
  'Ciobanesc Romanesc Mioritic',
  'Mocano',
  'Barac',
  'Central Asian Shepherd',
  'Tasi',
  'Tazy',
  'Sredneaziatskaya Borzaya',
  'Kazakhskaya Tazi',
  'Montenegrinische Gebirgsbracke',
  'Carlin',
  'Carlino',
  'Doguillo',
  'Perro Gocho',
  'Perro de los Paramos',
  'Nederlandse Kooikerhondje',
  'Swiss low -litter dog',
  'Bernese Lower Run dog smooth hair',
  'Bernese Lower Run dog Raughaar',
  'Jura Lower Run dog',
  'Lucerne Lower Run dog',
  'Schwyzer Lower Run dog',
  'Pohjanpystykorvat',
  'Sort Dyrehund',
  'Norsk Lundefund',
  'Nova Scotia Retriever',
  'Olde English Bulldog',
  'Leavitt Bulldog',
  'Hound',
  'Perdiguero Navarro',
  'Old Spanish Pointer',
  'Navarro Pointer',
  'Pachon de Victoria',
  'Pastor Vasco',
  'Euskal Artzain Txakurra',
  'Beijingesis',
  'Portuguese base dog',
  'Perro Turco',
  'Turkish dog',
  'Turco Andaluz',
  'Andalusian Turk',
  'Majorero Canario',
  'Perro Bardino Majorero',
  'Viringo',
  'Small basset Griffon Vendéen',
  'Little Blue Gascogne Drive Dog',
  'Brabant Griffon',
  'Canarian Podenco',
  'CA EIVISSEC',
  'Mallorqui',
  'Xarnelo',
  'Mayorquais',
  'Charnegue',
  'Charnegui',
  'Skin-poitou',
  'Polish Hound',
  'Brachet Polonais',
  'Sabueso Polaco',
  'Gonczy polski',
  'Polish Hunting Dog',
  'Polish scenthound',
  'Pon',
  'Chien de Franche-Comté',
  'Caniche',
  'Berger des Pyrenees a face rase',
  'Berger des Pyrenees a Poil Long',
  'Berger of the Pyrenees au Museau normal',
  'Patou',
  'Poligar Hound',
  'Rampuri',
  'Rampure',
  'Ratonero Andaluz',
  'Andalusian Mouse-Hunting Dog',
  'Bodeguero Andaluz',
  'Perro Ratonero Bodeguero',
  'Ratero',
  'GOS Rater Valencià',
  'Ca de Rater Valencia',
  'Russian toy',
  'Russian dwarf spaniel',
  'Moscow long -haired Toy Terrier',
  'Spanish drive dog',
  'Samoiedskaïa Sabaka',
  'Sapsaree',
  'Macedonian shepherd dog',
  'Save bracket',
  'Posavatz-Bracke',
  'Posavski Gonic',
  'Posavatz drive dog',
  'Nederlandse Schapendoes',
  'Dutch Schapendoes',
  'Schiller run dog',
  'Schiller-Bracke',
  'Russian terrier',
  'Chinese fighting dog',
  'Shiba',
  'Shikoku',
  'Kochi-Ken',
  'North African greyhound',
  'Oskai',
  'Oskay',
  'Smaland run dog',
  'Smaland bracket',
  'Irish Soft Coated Wheate Terrier',
  'Italian shear -haired upright dog',
  'Stabij',
  'Stbyhoun',
  'English Stafford',
  'Nurse maid',
  'Staff',
  'The Nanny Dog',
  'Staff',
  'Styrian Rauhhaarbracke',
  'Peintinger-Bracke',
  'South Russian Shepherd',
  'Ioujnorousskaïa Ovtcharka',
  'Kirghiz Barzoi',
  'Tajgan',
  'Tamascan Husky',
  'Tamascan Dog',
  'Tamaskan Wolf-Dog',
  'Finnish Tamaskan Dog',
  'Tibetan Terrier',
  'Tsang Apso',
  'Bosnian-Herzegovinian-Croatian Shepherd',
  'Tosa Ken',
  'Tosa token',
  'Tosa',
  'Japanese combat dog',
  'Treing Tennessee Brindle Coonhound',
  'West Gothspitz',
  'Swedish Cattle Dog',
  'Swedish Vallhund',
  'Italian Volpino',
  'Ci Defaid CymreiG',
  'Bugeilgi',
  'Welsh Collie',
  'White highland terrier',
  'Westie',
  'Poltal hole Terrier',
  'Roseath Terrier',
  'Wetterhond',
  'Little English greyhound',
  'Miniature Pinscher',
  'Minpine',
  'Minidoberman',
  'Rehrattler',
  'Staffordshire Terrier',
  'Cao de Fila',
  'Turkish shepherd dog',
  'Turkish German Shepherd',
  'Anatolian',
  'Sivas Kangal',
  'Tibetan mastiff',
  'Irish Staffordshire Terrier',
  'Canary Mastiff',
  'Mastine Canario',
  'Karakatsch',
  'SBT',
  'Mini Staffordshire Bull Terrier',
  'Staffordshire Bull Terrier',
  'Mastin de Aragon',
  'Alum',
  'Toy poodle',
  'Cocoon',
  'New English bulldog',
  'Small Greek Domestic Dog',
  'Retro-mops',
  'American cocker Spaniel',
  'Anglo-Français de Petite Vénerie',
  'Basset Artésien Normand',
  "Basset d'Artois",
  'Beagle-Harrier',
  'Bergamasker shepherd dog',
  'Bichon Frisé',
  'White Swiss Shepherd',
  'Bordeaux',
  'Chinese skip dog',
  'English Bulldog',
  'English Cocker Spaniel',
  'Pyrenea',
  'Foxterrier',
  'Franz. Rauhaariger Posschund',
  'Frisian',
  'Gold duties',
  'Greenland dog',
  'Great Münsterländer',
  'Haldenstøver',
  'Istrian Bracke',
  'Italian spinones',
  'Japan Spitz',
  'Kanaan dog',
  'Catalan Shepherd',
  'Labrador Retriever',
  'Long -haired collie',
  'Lapland reindeer dog',
  'Lion',
  'Maremmemen-Abruzzo-Schäferhund',
  'Nova Scotia Duck Tolling Retriever',
  'Parson Russell Terrier',
  'Pit Bull Terrier',
  'English Springer Spaniel',
  'Saarlooswolfhund',
  'Serbian drive dog',
  'Hair -haired Bosnian drive dog',
  'Tatra-Hirten dog',
  'Tibet spaniel',
  'Tibet terrier',
  'Alaskan Indian Dog',
  'Alternatively Bulldog',
  'Argentine Bulldogge',
  'Atlas Shepherd',
  'Basset Griffon Petit',
  'Basset Griffon Vendenen',
  'Bosnian bracket',
  'Bosnian Rauhhaarbracke',
  'Bouvier',
  'Braque Francais Type Gascogne',
  'Braque Francais type Pyrénées',
  'Bull terrier miniature',
  'Bull terrier Stafford Shire',
  'Coban shepherd dog',
  'Danish-Swedish court dog',
  'Wirehaar Fox Terrier',
  'English Pitbull Terrier',
  'Moose dog',
  'Ellenikos ichnilatis',
  'Fell Terrier',
  'Finnish reindeer dog dog',
  'Flemish driving dog',
  'German Shepherd',
  'Smooth hair fox terrier',
  'Griffon Bleu des Gascogne',
  'Griffon Korthals',
  'Harlekin Pudel',
  'Hertha pointer',
  'Dutch schnauzer',
  'Wooden bracket',
  'Irish Blue Terrier',
  'Istrian Shepherd',
  'Italian point',
  'Yugoslav three -color bracket',
  'Jura Type St. Hubert Laufhund',
  'Jura Type Bruno Drive Dog',
  'King Charles Cavalier',
  'Kishu',
  'Kobe-Terrier',
  'Kopov Bracke',
  'Shorthair Chow Chow',
  'Short hair',
  'Long -haired shepherd',
  'Langhaar Teckel',
  'Moscow dwarf terrier',
  'Old German Sheepdog',
  'Eastern Siberian Laika',
  'Austrian short hairpin',
  'Pannonic detection dog',
  'Persian greyhound',
  'Plot hound',
  'Podenco Grande',
  'Podengo Medio',
  'Podengo Pequeno',
  'Portuguese pointer',
  'Radhaar Teckel',
  'Rotweißer Irish Setter',
  'Scottish setter',
  'Shetland Shepherd',
  'Skye Silky Terrier',
  'Spanish pointer',
  'Tibet Apso',
  'Wolfs-chow',
  'Transylvanic sniffer dog',
  'Czech stitch hair',
  'Turkish herding dog',
  'Hungarian wire hair',
  'Hungarian short hair',
  'Vieräugl',
  'Welsh Hound',
  'West Country Harrier',
  'Alabai',
  'Alsatian',
  'Westfalerärier',
  'Bawarski Sokol',
  'Bond',
  'Berger Allemand',
  'Lucas Terrier',
  'Branchiero Siciliano',
  'Somerset Harrier',
  'Eskimohund',
  'Slovak bracket',
  'Set dog',
  'Russian bracket',
  'Russian hunting spaniel',
  'Jack Russel Parson',
  'Caucasian shepherd dog',
  'Presa Canario',
  'Cretan detection dog',
  'Portuguese shepherd dog',
  'Latvian bracket',
  'Lithuanian bracket',
  'Race not listed up to 44 cm',
  'Race not listed from 45 cm',
  'Mixed breed up to 44 cm',
  'Mixed breed from 45 cm',
  'Perro Lobo Herreno',
] as const;

export type Breeds = typeof breeds[number];

export const dangerousBreeds = [
  'American Pit Bull Terrier',
  'American Staffordshire Terrier',
  'Bullmastiff',
  'Bullterrier (any kind)',
  'Dogo Argentino',
  'Dogue de Bordeaux',
  'Fila Brasileiro',
  'Mastiff',
  'Mastine Espanol',
  'Mastino Napoletano',
  'Pit Bull Terrier',
  'Rottweiler',
  'Staffordshire Bull Terrier',
  'Tosa Inu',
  'English Bull Terrier',
  'Dwarf Bull Terrier',
  'Miniature Bull Terrier',
  'Mini bull terrier',
  'Mini Staffordshire Bull Terrier',
  'Pit Bull Terrier',
  'Bull terrier miniature',
  'Bull terrier Stafford Shire',
  'English Pitbull Terrier',
  'Bull terrier',
  'Pit bull terrier',
] as const;

export type DangerousBreeds = typeof dangerousBreeds[number];

export const dangerousBreedsSpain: Breeds[] = [
  'Tosa Inu',
  'Akita Inu',
  'Rottweiler',
  'Fila Brasileiro',
  'Dogo Argentino',
  'Pit Bull Terrier',
  'Staffordshire Bull Terrier',
  'American Staffordshire Terrier',
  'Doberman',
  'American Bully',
  'American Akita',
  'American Pit Bull Terrier',
  'Bordeaux Mastiff',
  'Tibetan mastiff',
  'Neapolitan Mastiff',
  'Perro de Presa Canario',
  'Perro de Presa Mallorquin',
  'Bull terrier',
  'Boxer',
  'Bullmastiff',
  'American bandogg mastiff',
] as const;

export type DangerousBreedsSpain = typeof dangerousBreedsSpain[number];
