export const LegalInsurers: string[] = [
  'ACE Automobil Club e.V.',
  'ADAC',
  'ADLER',
  'AdvoCard',
  'AIG EUROPE S.A. Paris',
  'AIOI Motor and General',
  'Allianz',
  'Allrecht',
  'Alte Leipziger',
  'A+M Versicherung',
  'ARAG',
  'Aspecta Versicherung AG',
  'Asstel',
  'AUXILIA',
  'AVD',
  'AXA',
  'AXA Alternative',
  'Baden-Badener',
  'BGV Badische Versicherungen',
  'Badische Gemeinde',
  'Basler',
  'Basler Securitas ROLAND',
  'Bayerische Beamten Versicherung',
  'Bayerische Hausbesitzer',
  'die Bayerische',
  'Bruderhilfe',
  'Concordia',
  'Condor Allgemeine',
  'Die Continentale',
  'Cosmos',
  'DA Deutsche Allgemeine',
  'D.A.S.',
  'DBV',
  'DBV-Winterthur',
  'Debeka',
  'Deurag',
  'DFV',
  'Deutsche Internet',
  'Deutscher Herold Allgemeine',
  'DEVK',
  'DEVK (Sach/HUK)',
  'Direct Line',
  'DMB',
  'EUROPA',
  'Europe Assistance',
  'Frankfurter Versicherungs AG (Frankfurter Allianz)',
  'GARANTA Versicherungs-AG',
  'GVO',
  'Generali Lloyd',
  'Generali',
  'Gerling-Konzern Allgemeine',
  'Gothaer Allgemeine Versicherungs AG',
  'GVV',
  'Hamburg Mannheimer',
  'Hanse Merkur Versicherung',
  'HDI Privat Versicherung AG',
  'HDI',
  'Helvetia (Schweizerische Versicherungsgesellschaft)',
  'Hiscox AG (Niederlassung für die Bundesrepublik Deutschland)',
  'HUK Coburg',
  'HUK24',
  'HUK-COBURG',
  'Ideal',
  'Ineas Insurance Company NV',
  'InterLloyd',
  'Itzehoer',
  'Jurpartner',
  'Karlsruher Beamten-Versicherung AG',
  'Karlsruher',
  'KRAVAG-SACH',
  'KS Kraftfahrer-Schutz',
  'Laeisz',
  'Landesschadenhilfe',
  'Lippische Landes-Brandversicherungsanstalt',
  'LVM',
  'Mannheimer Versicherung AG',
  'Mecklenburgische',
  'Medien Versicherung',
  'Merkur Assistance AG Holding',
  'Minerva',
  'Münchener Verein',
  'Neckermann Versicherungen',
  'NRV',
  'SIGNAL IDUNA',
  'Nürnberger Versicherung',
  'Öffentliche Feuerversicherung Sachsen-Anhalt',
  'ÖVB',
  'Oldenburgische Landesbank AG',
  'Oldenburgische Landesbrandkasse',
  'Optima Versicherung-AG',
  'ÖRAG',
  'OVAG',
  'Provinzial Nord Brandkasse',
  'Provinzial Versicherungsanstalt der Rheinprovinz',
  'Quelle Versicherung AG',
  'Rechtsschutz Union',
  'Rheinland Versicherungs AG',
  'Roland',
  'ROLAND Schutzbrief-Versicherung AG',
  'R+V',
  'SAARLAND Feuerversicherung AG',
  'SCHWEIZER-NATIONAL',
  'Sicher Direkt Roland',
  'Sparkassen-Versicherung Sachsen',
  'Sparkassen DirektVersicherung',
  'SV SparkassenVersicherung Hessen-Nassau-Thüringen',
  'Telcon Versicherung AG',
  'Transatlantische Allgemeine Versicherung AG',
  'Ülzener Allgemeine',
  'Vereinte Spezial Versicherung AG',
  'VGH Versicherungen',
  'VHV',
  'Volksfürsorge Deutsche Lebensversicherung AG',
  'Volkswohl Bund Versicherungen',
  'Westfälische Provinzial Versicherung',
  'Württembergische Gemeinde-Versicherung',
  'Württembergische und Badische',
  'Württembergische',
  'Württembergische Versicherungen',
  'Zurich',
  '9999 wenn VU nicht bekannt',
];
