export const regions = [
  'at', // Austria
  'be', // Belgium
  'bg', // Bulgaria
  'hr', // Croatia
  'cy', // Cyprus
  'cz', // Czechia
  'de', // Germany
  'dk', // Denmark
  'ee', // Estonia
  'es', // Spain
  'fi', // Finland
  'fr', // France
  'gr', // Greece
  'hu', // Hungary
  'ie', // Ireland
  'it', // Italy
  'lt', // Lithuania
  'lu', // Luxembourg
  'lv', // Latvia
  'mt', // Malta
  'nl', // Netherlands
  'pl', // Poland
  'pt', // Portugal
  'ro', // Romania
  'si', // Slovenia
  'se', // Sweden
  'sk', // Slovakia
  'mc', // Monaco
  'eu', // Europe
] as const;
export type Region = typeof regions[number];
