// This is an auto-generated file, pleased don't update it manually
export const universities = [
  'AKAD Hochschule Stuttgart - staatlich anerkannt',
  'APOLLON Hochschule der Gesundheitswirtschaft',
  'Akademie der Bildenden Künste München',
  'Akademie der Bildenden Künste Nürnberg',
  'Akademie der Polizei Hamburg',
  'Akkon-Hochschule',
  'Alanus Hochschule für Kunst und Gesellschaft',
  'Albert-Ludwigs-Universität Freiburg im Breisgau',
  'Alice Salomon Hochschule Berlin',
  'Allensbach Hochschule Konstanz,  staatlich anerkannte Hochschule der European Education Group GmbH',
  'Archivschule Marburg - Hochschule für Archivwissenschaft',
  'Augustana-Hochschule Neuendettelsau',
  'BSP Business and Law School - Hochschule für Management und Recht',
  'Bard College Berlin, A Liberal Arts University',
  'Barenboim-Said Akademie',
  'Bauhaus-Universität Weimar',
  'Bergische Universität Wuppertal',
  'Berlin International University of Applied Sciences',
  'Berliner Hochschule für Technik',
  'Berufliche Hochschule Hamburg (BHH)',
  'Brand University of Applied Sciences',
  'Brandenburgische Technische Universität Cottbus-Senftenberg',
  'Bucerius Law School, Hochschule für Rechtswissenschaft',
  'Burg Giebichenstein Kunsthochschule Halle',
  'CBS International Business School - University of Applied Sciences',
  'CODE University of Applied Sciences',
  'CVJM-Hochschule',
  'Carl von Ossietzky Universität Oldenburg',
  'Charlotte Fresenius Hochschule',
  'Christian-Albrechts-Universität zu Kiel',
  'Constructor University',
  'DEKRA Hochschule für Medien',
  'DHGS Deutsche Hochschule für Gesundheit und Sport',
  'DIPLOMA Hochschule - Private Fachhochschule Nordhessen',
  'DIU - Dresden International University GmbH',
  'Deutsche Hochschule der Polizei',
  'Deutsche Hochschule für Prävention und Gesundheitsmanagement GmbH',
  'Deutsche Sporthochschule Köln',
  'Deutsche Universität für Verwaltungswissenschaften Speyer',
  'Digital Business University of Applied Sciences',
  'Duale Hochschule Baden-Württemberg',
  'Duale Hochschule Gera-Eisenach',
  'Duale Hochschule Schleswig-Holstein - staatlich anerkannte Hochschule für angewandte Wissenschaften in Trägerschaft der Wirtschaftsakademie Schleswig-Holstein',
  'EBS Universität für Wirtschaft und Recht',
  'EBZ Business School - University of Applied Sciences',
  'ESCP Europe Wirtschaftshochschule Berlin e.V.',
  'ESMT European School of Management and Technology',
  'Eberhard Karls Universität Tübingen',
  'Ernst-Abbe-Hochschule Jena - University of Applied Sciences',
  'Europa-Universität Flensburg',
  'Europa-Universität Viadrina Frankfurt (Oder)',
  'Europäische Fachhochschule Rhein/Erft, european university of applied sciences',
  'Europäische Fernhochschule Hamburg',
  'Evangelische Hochschule Berlin',
  'Evangelische Hochschule Darmstadt (staatlich anerkannt) – Kirchliche Körperschaft des öffentlichen Rechts',
  'Evangelische Hochschule Dresden',
  'Evangelische Hochschule Freiburg, staatlich anerkannte Hochschule der Evangelischen Landeskirche in Baden',
  'Evangelische Hochschule Ludwigsburg - staatlich anerkannte Hochschule für Angewandte Wissenschaften der Evangelischen Landeskirche in Württemberg',
  'Evangelische Hochschule Rheinland-Westfalen-Lippe',
  'Evangelische Hochschule Tabor',
  'Evangelische Hochschule für Kirchenmusik',
  'Evangelische Hochschule für Soziale Arbeit & Diakonie',
  'Evangelische Hochschule für angewandte Wissenschaften - Evangelische Fachhochschule Nürnberg',
  'FH Münster University of Applied Sciences',
  'FOM Hochschule für Oekonomie & Management - University of Applied Sciences',
  'Fachhochschule Aachen',
  'Fachhochschule Dortmund',
  'Fachhochschule Dresden',
  'Fachhochschule Erfurt',
  'Fachhochschule Kiel',
  'Fachhochschule Polizei Sachsen-Anhalt',
  'Fachhochschule Potsdam',
  'Fachhochschule Südwestfalen',
  'Fachhochschule Wedel',
  'Fachhochschule Westküste, Hochschule für Wirtschaft und Technik',
  'Fachhochschule der Diakonie - Diaconia - University of Applied Sciences',
  'Fachhochschule der Polizei Brandenburg',
  'Fachhochschule der Verwaltung des Saarlandes',
  'Fachhochschule der Wirtschaft',
  'Fachhochschule des Mittelstands (FHM)',
  'Fachhochschule für Finanzen Brandenburg',
  'Fachhochschule für Interkulturelle Theologie Hermannsburg',
  'Fachhochschule für Rechtspflege Nordrhein-Westfalen',
  'Fachhochschule für Sport und Management Potsdam',
  'Fachhochschule für Verwaltung und Dienstleistung in Schleswig-Holstein',
  'Fachhochschule für die Wirtschaft Hannover',
  'Fachhochschule für öffentliche Verwaltung, Polizei und Rechtspflege des Landes Mecklenburg-Vorpommern',
  'FernUniversität in Hagen',
  'Filmuniversität Babelsberg Konrad Wolf',
  'Fliedner Fachhochschule Düsseldorf',
  'Folkwang Universität der Künste',
  'Frankfurt School of Finance & Management',
  'Frankfurt University of Applied Sciences',
  'Freie Hochschule Stuttgart - Seminar für Waldorfpädagogik. Staatlich anerkannte wissenschaftliche Hochschule.',
  'Freie Theologische Hochschule Gießen',
  'Freie Universität Berlin',
  'Friedrich-Alexander-Universität Erlangen-Nürnberg',
  'Friedrich-Schiller-Universität Jena',
  'GISMA Business School',
  'Georg-August-Universität Göttingen',
  'Gottfried Wilhelm Leibniz Universität Hannover',
  'HAWK Hochschule für angewandte Wissenschaft und Kunst Hildesheim/Holzminden/Göttingen',
  'HHL Leipzig Graduate School of Management',
  'HMKW Hochschule für Medien, Kommunikation und Wirtschaft',
  'HMU Health and Medical University',
  'HSBA Hamburg School of Business Administration',
  'HSD Hochschule Döpfer',
  'HafenCity Universität Hamburg',
  'Hamburger Fern-Hochschule, gemeinnützige GmbH',
  'Heinrich-Heine-Universität Düsseldorf',
  'Helmut-Schmidt-Universität/Universität der Bundeswehr Hamburg',
  'Hertie School',
  'Hessische Hochschule für Finanzen und Rechtspflege Rotenburg a.d. Fulda',
  'Hessische Hochschule für öffentliches Management und Sicherheit',
  'Hochschule  für  angewandte  Wissenschaften  Weihenstephan-Triesdorf',
  'Hochschule Aalen - Technik und Wirtschaft',
  'Hochschule Albstadt-Sigmaringen',
  'Hochschule Anhalt - Anhalt University of Applied Sciences',
  'Hochschule Biberach - Hochschule für Architektur und Bauwesen, Betriebswirtschaft und Biotechnologie',
  'Hochschule Bielefeld - University of Applied Sciences and Arts (HSBI)',
  'Hochschule Bochum - University of Applied Sciences',
  'Hochschule Bonn-Rhein-Sieg, University of Applied Sciences',
  'Hochschule Braunschweig/Wolfenbüttel, Ostfalia Hochschule für angewandte Wissenschaften',
  'Hochschule Bremen',
  'Hochschule Bremerhaven',
  'Hochschule Clara Hoffbauer (HCHP) - University of Applied Sciences',
  'Hochschule Darmstadt',
  'Hochschule Düsseldorf',
  'Hochschule Emden/Leer',
  'Hochschule Esslingen',
  'Hochschule Flensburg',
  'Hochschule Fresenius',
  'Hochschule Fresenius Heidelberg – staatlich anerkannte Hochschule der Hochschule Fresenius für Internationales Management GmbH',
  'Hochschule Fulda - University of Applied Sciences',
  'Hochschule Furtwangen - Informatik, Technik, Wirtschaft, Medien, Gesundheit',
  'Hochschule Geisenheim',
  'Hochschule Hamm-Lippstadt',
  'Hochschule Hannover',
  'Hochschule Harz, Hochschule für angewandte Wissenschaften (FH)',
  'Hochschule Heilbronn, Technik, Wirtschaft, Informatik',
  'Hochschule Kaiserslautern (University of Applied Sciences)',
  'Hochschule Karlsruhe - Technik und Wirtschaft',
  'Hochschule Koblenz',
  'Hochschule Konstanz Technik, Wirtschaft und Gestaltung',
  'Hochschule Landshut - Hochschule für angewandte Wissenschaften',
  'Hochschule Macromedia - staatlich anerkannte Hochschule für angewandte Wissenschaften der Macromedia GmbH mit Sitz in Stuttgart',
  'Hochschule Magdeburg-Stendal',
  'Hochschule Mainz',
  'Hochschule Mannheim',
  'Hochschule Merseburg',
  'Hochschule Mittweida, University of Applied Sciences',
  'Hochschule Neubrandenburg - University of Applied Sciences',
  'Hochschule Niederrhein',
  'Hochschule Nordhausen',
  'Hochschule Osnabrück',
  'Hochschule Pforzheim - Gestaltung, Technik, Wirtschaft und Recht',
  'Hochschule Ravensburg-Weingarten',
  'Hochschule Reutlingen, Hochschule für Technik-  Wirtschaft-Informatik-Design',
  'Hochschule Rhein-Waal - University of Applied Sciences',
  'Hochschule RheinMain',
  'Hochschule Ruhr West- University of Applied Sciences',
  'Hochschule Schmalkalden',
  'Hochschule Stralsund',
  'Hochschule Trier - Trier University of Applied Sciences',
  'Hochschule Weserbergland',
  'Hochschule Wismar - University of Applied Sciences: Technology, Business and Design',
  'Hochschule Worms, University of Applied Sciences',
  'Hochschule Zittau/Görlitz',
  'Hochschule der Bayerischen Wirtschaft für angewandte Wissenschaften - HDBW',
  'Hochschule der Bildenden Künste Saar',
  'Hochschule der Bundesagentur für Arbeit - Staatlich anerkannte Hochschule für angewandte Wissenschaft in Mannheim und Schwerin (University of Applied Labour Studies of the Federal Employment Agency)',
  'Hochschule der Deutschen Bundesbank',
  'Hochschule der Medien Stuttgart',
  'Hochschule der Polizei Rheinland-Pfalz',
  'Hochschule der Sächsischen Polizei (FH)',
  'Hochschule der Wirtschaft für Management',
  'Hochschule der bildenden Künste (HBK) Essen',
  'Hochschule des Bundes für öffentliche Verwaltung',
  'Hochschule für Angewandte Wissenschaften Hamburg',
  'Hochschule für Angewandte Wissenschaften Hof',
  'Hochschule für Bildende Künste (Städelschule)',
  'Hochschule für Bildende Künste Braunschweig',
  'Hochschule für Bildende Künste Dresden',
  'Hochschule für Bildende Künste Hamburg',
  'Hochschule für Fernsehen und Film München',
  'Hochschule für Finanzen NRW',
  'Hochschule für Finanzen Rheinland-Pfalz',
  'Hochschule für Finanzwirtschaft & Management',
  'Hochschule für Forstwirtschaft Rottenburg',
  'Hochschule für Gesellschaftsgestaltung',
  'Hochschule für Gestaltung Offenbach',
  'Hochschule für Gestaltung Schwäbisch Gmünd',
  'Hochschule für Gesundheit - University of Applied Sciences',
  'Hochschule für Grafik und Buchkunst Leipzig',
  'Hochschule für Jüdische Studien Heidelberg',
  'Hochschule für Katholische Kirchenmusik und Musikpädagogik',
  'Hochschule für Kirchenmusik der Diözese Rottenburg-Stuttgart',
  'Hochschule für Kirchenmusik der Evangelisch-Lutherischen Landeskirche Sachsens',
  'Hochschule für Kirchenmusik der Evangelischen Kirche von Westfalen',
  'Hochschule für Kirchenmusik der Evangelischen Landeskirche in Baden',
  'Hochschule für Kirchenmusik der Evangelischen Landeskirche in Württemberg',
  'Hochschule für Kommunikation und Gestaltung',
  'Hochschule für Künste Bremen',
  'Hochschule für Künste im Sozialen, Ottersberg',
  'Hochschule für Musik Carl Maria von Weber Dresden',
  'Hochschule für Musik Detmold',
  'Hochschule für Musik Franz Liszt Weimar',
  'Hochschule für Musik Freiburg im Breisgau',
  'Hochschule für Musik Hanns Eisler Berlin',
  'Hochschule für Musik Karlsruhe',
  'Hochschule für Musik Nürnberg',
  'Hochschule für Musik Saar',
  'Hochschule für Musik Würzburg',
  'Hochschule für Musik und Darstellende Kunst Frankfurt am Main',
  'Hochschule für Musik und Tanz Köln',
  'Hochschule für Musik und Theater Felix Mendelssohn Bartholdy Leipzig',
  'Hochschule für Musik und Theater Hamburg',
  'Hochschule für Musik und Theater München',
  'Hochschule für Musik und Theater Rostock',
  'Hochschule für Musik, Theater und Medien Hannover',
  'Hochschule für Philosophie',
  'Hochschule für Polizei Baden-Württemberg',
  'Hochschule für Polizei und öffentliche Verwaltung Nordrhein-Westfalen',
  'Hochschule für Rechtspflege Schwetzingen',
  'Hochschule für Schauspielkunst Ernst Busch',
  'Hochschule für Technik Stuttgart',
  'Hochschule für Technik und Wirtschaft Berlin',
  'Hochschule für Technik und Wirtschaft Dresden - University of Applied Sciences',
  'Hochschule für Technik und Wirtschaft des Saarlandes',
  'Hochschule für Technik, Wirtschaft und Kultur Leipzig',
  'Hochschule für Technik, Wirtschaft und Medien Offenburg',
  'Hochschule für Wirtschaft und Gesellschaft Ludwigshafen ',
  'Hochschule für Wirtschaft und Recht Berlin',
  'Hochschule für Wirtschaft und Umwelt Nürtingen-Geislingen',
  'Hochschule für angewandte Pädagogik',
  'Hochschule für angewandte Wissenschaften Ansbach',
  'Hochschule für angewandte Wissenschaften Augsburg - University of Applied Sciences',
  'Hochschule für angewandte Wissenschaften Coburg',
  'Hochschule für angewandte Wissenschaften Kempten',
  'Hochschule für angewandte Wissenschaften München',
  'Hochschule für angewandte Wissenschaften Neu-Ulm',
  'Hochschule für angewandtes Management',
  'Hochschule für den öffentlichen Dienst in Bayern',
  'Hochschule für evangelische Kirchenmusik der Evangelisch-Lutherischen Kirche in Bayern',
  'Hochschule für nachhaltige Entwicklung Eberswalde',
  'Hochschule für Öffentliche Verwaltung Bremen',
  'Hochschule für öffentliche Verwaltung Kehl',
  'Hochschule für öffentliche Verwaltung Rheinland-Pfalz',
  'Hochschule für öffentliche Verwaltung und Finanzen Ludwigsburg',
  'Hochschule für öffentliche Verwaltung und Rechtspflege (FH), Fortbildungszentrum des Freistaates Sachsen',
  'Humboldt-Universität zu Berlin',
  'IB Hochschule für Gesundheit und Soziales',
  'IST-Hochschule für Management',
  'IU Internationale Hochschule',
  'International Psychoanalytic University Berlin',
  'International School of Management',
  'Internationale Hochschule Liebenzell (IHL)',
  'Internationale Hochschule SDI München - Hochschule für angewandte Wissenschaften',
  'Jade Hochschule -  Wilhelmshaven/Oldenburg/Elsfleth',
  'Johann Wolfgang Goethe-Universität, Frankfurt am Main',
  'Johannes Gutenberg-Universität Mainz',
  'Julius-Maximilians-Universität Würzburg',
  'Justus-Liebig-Universität Gießen',
  'Karlshochschule International University - staatlich anerkannte Hochschule der Karlshochschule gemeinnützige GmbH Karlsruhe',
  'Karlsruher Institut für Technologie',
  'Katholische    Stiftungshochschule für   angewandte Wissenschaften München - Hochschule der Kirchlichen Stiftung des öffentlichen Rechts Katholische Bildungsstätten für Sozialberufe in Bayern',
  'Katholische Hochschule Freiburg, staatlich anerkannte Hochschule - Catholic University of Applied Sciences',
  'Katholische Hochschule Mainz Catholic University of Applied Sciences',
  'Katholische Hochschule Nordrhein-Westfalen - Catholic University of Applied Sciences',
  'Katholische Hochschule für Sozialwesen Berlin (KHSB) - Staatlich anerkannte Fachhochschule für Sozialwesen',
  'Katholische Universität Eichstätt - Ingolstadt',
  'Kirchliche Hochschule Wuppertal',
  'Kolping Hochschule',
  'Kommunale Hochschule für Verwaltung in Niedersachsen',
  'Kunstakademie Düsseldorf',
  'Kunstakademie Münster, Hochschule für Bildende Künste',
  'Kunsthochschule für Medien Köln',
  'Kölner Hochschule für Katholische Theologie (KHKT)',
  'Kühne Logistics University - Wissenschaftliche Hochschule für Logistik und Unternehmensführung',
  'Leibniz-Fachhochschule',
  'Leuphana Universität Lüneburg',
  'Ludwig-Maximilians-Universität München',
  'Lutherische Theologische Hochschule Oberursel',
  'MSH Medical School Hamburg - University of Applied Sciences and Medical University',
  'Martin-Luther-Universität Halle-Wittenberg',
  'Mediadesign Hochschule für Design und Informatik',
  'Medical School Berlin - Hochschule für Gesundheit und Medizin (MSB)',
  'Medizinische Hochschule Brandenburg Theodor Fontane',
  'Medizinische Hochschule Hannover (MHH)',
  'Merz Akademie Hochschule für Gestaltung, Kunst und Medien, Stuttgart - Staatlich anerkannt',
  'Munich Business School - Staatlich anerkannte private Fachhochschule',
  'Musikhochschule Lübeck',
  'Muthesius Kunsthochschule',
  'NBS Northern Business School – University of Applied Sciences',
  'Nordakademie - Staatlich anerkannte private Fachhochschule mit dualen Studiengängen',
  'Norddeutsche Akademie für Finanzen und Steuerrecht',
  'Norddeutsche Hochschule für Rechtspflege - Niedersachsen',
  'Ostbayerische Technische Hochschule Amberg-Weiden',
  'Ostbayerische Technische Hochschule Regensburg',
  'Otto-Friedrich-Universität Bamberg',
  'Otto-von-Guericke-Universität Magdeburg',
  'PFH - Private Hochschule Göttingen',
  'Palucca Hochschule für Tanz Dresden',
  'Philipps-Universität Marburg',
  'Philosophisch-Theologische Hochschule Münster - Kirchlich und staatlich anerkannte Hochschule in Trägerschaft der PTH Philosophisch-Theologische Hochschule Münster gemeinnützige GmbH',
  'Philosophisch-Theologische Hochschule Sankt Georgen Frankfurt am Main',
  'Polizeiakademie Niedersachsen',
  'Private Hochschule für Wirtschaft und Technik Vechta/Diepholz',
  'Private Universität Witten/Herdecke gGmbH',
  'Provadis School of International Management and Technology',
  'Psychologische Hochschule Berlin (PHB)',
  'Pädagogische Hochschule Freiburg',
  'Pädagogische Hochschule Heidelberg',
  'Pädagogische Hochschule Karlsruhe',
  'Pädagogische Hochschule Ludwigsburg',
  'Pädagogische Hochschule Schwäbisch Gmünd',
  'Pädagogische Hochschule Weingarten',
  'Quadriga Hochschule Berlin',
  'Rheinisch-Westfälische Technische Hochschule Aachen',
  'Rheinische Fachhochschule Köln',
  'Rheinische Friedrich-Wilhelms-Universität Bonn',
  'Rheinland-Pfälzische Technische Universität Kaiserslautern-Landau',
  'Robert-Schumann-Hochschule Düsseldorf',
  'Ruhr-Universität Bochum',
  'Ruprecht-Karls-Universität Heidelberg',
  'SRH Berlin University of Applied Sciences',
  'SRH Fernhochschule - The Mobile University',
  'SRH Hochschule Heidelberg - Staatlich anerkannte Fachhochschule',
  'SRH Hochschule für Gesundheit',
  'SRH Hochschule in Nordrhein-Westfalen',
  'SRH Wilhelm Löhe Hochschule',
  'Staatliche Akademie der Bildenden Künste Karlsruhe',
  'Staatliche Akademie der Bildenden Künste Stuttgart',
  'Staatliche Hochschule für Gestaltung Karlsruhe',
  'Staatliche Hochschule für Musik Trossingen',
  'Staatliche Hochschule für Musik und Darstellende Kunst Mannheim',
  'Staatliche Hochschule für Musik und Darstellende Kunst Stuttgart',
  'Steinbeis-Hochschule',
  'Steuerakademie Niedersachsen',
  'Stiftung Tierärztliche Hochschule Hannover',
  'Technische Hochschule Aschaffenburg',
  'Technische Hochschule Bingen',
  'Technische Hochschule Brandenburg',
  'Technische Hochschule Deggendorf',
  'Technische Hochschule Georg Agricola',
  'Technische Hochschule Ingolstadt',
  'Technische Hochschule Köln',
  'Technische Hochschule Lübeck',
  'Technische Hochschule Mittelhessen - THM',
  'Technische Hochschule Nürnberg Georg Simon Ohm',
  'Technische Hochschule Ostwestfalen-Lippe ',
  'Technische Hochschule Rosenheim',
  'Technische Hochschule Ulm',
  'Technische Hochschule Wildau',
  'Technische Hochschule Würzburg-Schweinfurt',
  'Technische Universität Bergakademie Freiberg',
  'Technische Universität Berlin',
  'Technische Universität Carolo-Wilhelmina zu Braunschweig',
  'Technische Universität Chemnitz',
  'Technische Universität Clausthal',
  'Technische Universität Darmstadt',
  'Technische Universität Dortmund',
  'Technische Universität Dresden',
  'Technische Universität Hamburg',
  'Technische Universität Ilmenau',
  'Technische Universität München',
  'Theologische Fakultät Fulda',
  'Theologische Fakultät Paderborn',
  'Theologische Fakultät Trier',
  'Theologische Hochschule Elstal',
  'Theologische Hochschule Friedensau',
  'Theologische Hochschule Reutlingen - staatlich anerkannte Fachhochschule der Evangelisch-methodistischen Kirche',
  'Theologisches Hochschule Ewersbach',
  'Thüringer Fachhochschule für öffentliche Verwaltung',
  'Touro College Berlin',
  'University of Europe for Applied Sciences',
  'University of Labour',
  'Universität Augsburg',
  'Universität Bayreuth',
  'Universität Bielefeld',
  'Universität Bremen',
  'Universität Duisburg-Essen',
  'Universität Erfurt',
  'Universität Greifswald',
  'Universität Hamburg',
  'Universität Hildesheim',
  'Universität Hohenheim',
  'Universität Kassel',
  'Universität Koblenz',
  'Universität Konstanz',
  'Universität Leipzig',
  'Universität Mannheim',
  'Universität Osnabrück',
  'Universität Paderborn',
  'Universität Passau',
  'Universität Potsdam',
  'Universität Regensburg',
  'Universität Rostock',
  'Universität Siegen',
  'Universität Stuttgart',
  'Universität Trier',
  'Universität Ulm',
  'Universität Vechta',
  'Universität der Bundeswehr München',
  'Universität der Künste Berlin',
  'Universität des Saarlandes',
  'Universität zu Köln',
  'Universität zu Lübeck',
  'VICTORIA | Internationale Hochschule',
  'VWA-Hochschule für berufsbegleitendes Studium',
  'Vinzenz Pallotti University',
  'WHU - Otto Beisheim School of Management',
  'Westfälische Hochschule Gelsenkirchen, Bocholt, Recklinghausen',
  'Westfälische Wilhelms-Universität Münster',
  'Westsächsische Hochschule Zwickau',
  'Wilhelm Büchner Hochschule - Private Fernhochschule Darmstadt',
  'XU Exponential University of Applied Sciences',
  'Zeppelin Universität - Hochschule zwischen Wirtschaft, Kultur und Politik',
  'accadis Hochschule Bad Homburg',
  'bbw Hochschule',
  'hochschule 21',
  'media Akademie - Hochschule Stuttgart',
  'weißensee kunsthochschule berlin',
];
