export const universities = [
  'accadis Hochschule Bad Homburg',
  'AKAD University Stuttgart',
  'Akademie der Bildenden Künste',
  'Akademie der Bildenden Künste München',
  'Akademie Deutsche POP',
  'Akademie für Darstellende Kunst Baden-Württemberg',
  'Akademie für Musik, Berlin',
  'Akademie für Tonkunst',
  'Akademisches Lehrinstitut für Psychologie',
  'Akkon-Hochschule',
  'Alanus Hochschule für Kunst und Gesellschaft',
  'Alanus Hochschule Studienzentrum Mannheim',
  'Albert-Ludwigs-Universität Freiburg im Breisgau',
  'Alice Salomon Hochschule Berlin',
  'Allensbach Hochschule Konstanz',
  'AMD Akademie Mode & Design',
  'APOLLON Hochschule der Gesundheitswirtschaft',
  'Arden University, Berlin',
  'ASW – Berufsakademie Saarland',
  'Athanor Akademie',
  'Augustana-Hochschule',
  'Bard College Berlin',
  'BAU International Berlin',
  'Bauhaus-Universität Weimar',
  'bbw Hochschule',
  'Bergische Universität Wuppertal',
  'Berlin International University of Applied Sciences',
  'Beruafsakademie Sachsen - Staatliche Studienakademie Bautzen',
  'Berufsakademie Hamburg',
  'Berufsakademie Sachsen - Staatliche Studienakademie Breitenbrunn',
  'Berufsakademie Sachsen - Staatliche Studienakademie Dresden',
  'Berufsakademie Sachsen - Staatliche Studienakademie Glauchau',
  'Berufsakademie Sachsen - Staatliche Studienakademie Plauen',
  'Berufsakademie Sachsen - Staatliche Studienakademie Riesa',
  'BEST-Sabel-Hochschule Berlin',
  'Beuth Hochschule für Technik Berlin',
  'Brand Academy - Hochschule für Design und Kommunikation',
  'Brandenburgische Technische Universität Cottbus-Senftenberg',
  'Brandenburgische Technische Universität Cottbus-Senftenberg - Campus Cottbus/Sachsendorf',
  'Brandenburgische Technische Universität Cottbus-Senftenberg - Campus Senftenberg',
  'BSP Business School Berlin - Hochschule für Management GmbH',
  'BSP Business School Berlin Potsdam – Campus Hamburg',
  'Bucerius Law School - Hochschule für Rechtswissenschaft',
  'Burg Giebichenstein Kunsthochschule Halle',
  'Carl von Ossietzky Universität Oldenburg',
  'Catalyst Institute for Creative Arts and Technology, Berlin',
  'Christian-Albrechts-Universität zu Kiel',
  'Cologne Business School (CBS)',
  'Cusanus Hochschule',
  'CVJM-Hochschule',
  'DEKRA Hochschule Berlin',
  'design akademie berlin - SRH Hochschule für Kommunikation und Design',
  'Designhochschule Leipzig',
  'Designhochschule Schwerin',
  'Deutsche Hochschule für Prävention und Gesundheitsmanagement',
  'Deutsche Hochschule für Verwaltungswissenschaften Speyer',
  'Deutsche Sporthochschule Köln',
  'DHGS Deutsche Hochschule für Gesundheit und Sport',
  'die medienakademie',
  'DIPLOMA Hochschule - Private Fachhochschule Nordhessen',
  'DIPLOMA Hochschule - Studienzentrum Aalen',
  'DIPLOMA Hochschule - Studienzentrum Altdorf bei Nürnberg',
  'DIPLOMA Hochschule - Studienzentrum Baden-Baden',
  'DIPLOMA Hochschule - Studienzentrum Berlin',
  'DIPLOMA Hochschule - Studienzentrum Bonn',
  'DIPLOMA Hochschule - Studienzentrum Friedrichshafen',
  'DIPLOMA Hochschule - Studienzentrum Hamburg',
  'DIPLOMA Hochschule - Studienzentrum Hannover',
  'DIPLOMA Hochschule - Studienzentrum Heilbronn',
  'DIPLOMA Hochschule - Studienzentrum Kassel',
  'DIPLOMA Hochschule - Studienzentrum Leipzig',
  'DIPLOMA Hochschule - Studienzentrum Mannheim',
  'DIPLOMA Hochschule - Studienzentrum München',
  'DIPLOMA Hochschule - Studienzentrum Schwentinental / Kiel',
  'DIPLOMA Hochschule - Studienzentrum Wuppertal',
  'DIU - Dresden International University GmbH',
  'Donau-Universität Krems',
  'DPFA Hochschule Sachsen',
  'Duale Hochschule Baden-Württemberg Heidenheim',
  'Duale Hochschule Baden-Württemberg Heilbronn',
  'Duale Hochschule Baden-Württemberg Karlsruhe',
  'Duale Hochschule Baden-Württemberg Lörrach',
  'Duale Hochschule Baden-Württemberg Mannheim',
  'Duale Hochschule Baden-Württemberg Mosbach',
  'Duale Hochschule Baden-Württemberg Mosbach - Campus Bad Mergentheim',
  'Duale Hochschule Baden-Württemberg Ravensburg',
  'Duale Hochschule Baden-Württemberg Ravensburg - Campus Friedrichshafen',
  'Duale Hochschule Baden-Württemberg Stuttgart',
  'Duale Hochschule Baden-Württemberg Stuttgart - Campus Horb',
  'Duale Hochschule Baden-Württemberg Villingen-Schwenningen',
  'Duale Hochschule Gera-Eisenach',
  'EBC Hochschule Campus Berlin',
  'EBC Hochschule Campus Düsseldorf',
  'EBC Hochschule Campus Hamburg',
  'Eberhard-Karls-Universität Tübingen',
  'EBS Universität für Wirtschaft und Recht',
  'EBS Universität für Wirtschaft und Recht - Campus Rheingau',
  'EBZ Business School',
  'Ernst-Abbe-Hochschule Jena',
  'Ernst-Moritz-Arndt-Universität Greifswald',
  'ESCP Europe Wirtschaftshochschule Berlin e.V.',
  'ESMT European School of Management and Technology',
  'EU Business School',
  'Euro Akademie Altenburg',
  'Euro Akademie Aschaffenburg',
  'Euro Akademie Bamberg',
  'Euro Akademie Berlin',
  'Euro Akademie Bitterfeld-Wolfen',
  'Euro Akademie Chemnitz',
  'Euro Akademie Dessau-Roßlau',
  'Euro Akademie Dortmund',
  'Euro Akademie Dresden',
  'Euro Akademie Erfurt',
  'Euro Akademie Gera',
  'Euro Akademie Görlitz',
  'Euro Akademie Halle',
  'Euro Akademie Hannover',
  'Euro Akademie Hohenstein-Ernstthal',
  'Euro Akademie Jena',
  'Euro Akademie Leipzig',
  'Euro Akademie Magdeburg',
  'Euro Akademie Mainz',
  'Euro Akademie Meißen',
  'Euro Akademie Nürnberg',
  'Euro Akademie Oldenburg',
  'Euro Akademie Pößneck',
  'Euro Akademie Riesa',
  'Euro Akademie Rochlitz',
  'Euro Akademie Tauberbischofsheim',
  'Euro Akademie Trier',
  'Euro Akademie Weißenfels',
  'Euro Akademie Wiesbaden',
  'Euro Akademie Wittenberg',
  'Euro Akademie Zerbst',
  'Euro Akademie Zittau',
  'Euro Akademie Zwickau',
  'Europa-Universität Flensburg',
  'Europa-Universität Viadrina Frankfurt (Oder)',
  'European Management School',
  'Europäische Fachhochschule Campus Aachen',
  'Europäische Fachhochschule Campus Brühl',
  'Europäische Fachhochschule Campus Köln',
  'Europäische Fachhochschule Campus Neuss',
  'Europäische Fachhochschule | MED',
  'Europäische Fernhochschule Hamburg',
  'Europäische Medien- und Business-Akademie Berlin',
  'Europäische Medien- und Business-Akademie Düsseldorf',
  'Europäische Medien- und Business-Akademie Hamburg',
  'Evangelische Fachhochschule Rheinland-Westfalen-Lippe',
  'Evangelische Hochschule Berlin',
  'Evangelische Hochschule Darmstadt',
  'Evangelische Hochschule Darmstadt in Schwalmstadt',
  'Evangelische Hochschule Dresden',
  'Evangelische Hochschule Freiburg',
  'Evangelische Hochschule für Kirchenmusik',
  'Evangelische Hochschule für Soziale Arbeit & Diakonie',
  'Evangelische Hochschule Ludwigsburg, Hochschule für Soziale Arbeit, Diakonie und Religionspädagogik',
  'Evangelische Hochschule Moritzburg',
  'Evangelische Hochschule Nürnberg',
  'Evangelische Hochschule Tabor',
  'Fachhochschule Aachen (FH)',
  'Fachhochschule Aachen in Jülich',
  'Fachhochschule Bielefeld',
  'Fachhochschule Bielefeld - Campus Minden',
  'Fachhochschule Bielefeld - Studienort Gütersloh',
  'Fachhochschule Clara Hoffbauer Potsdam',
  'Fachhochschule der Diakonie - Diaconia',
  'Fachhochschule der Wirtschaft',
  'Fachhochschule der Wirtschaft - Bergisch Gladbach',
  'Fachhochschule der Wirtschaft - Bielefeld',
  'Fachhochschule des Mittelstandes (FHM)',
  'Fachhochschule des Mittelstands (FHM) - Campus Bamberg',
  'Fachhochschule des Mittelstands (FHM) - Campus Hannover',
  'Fachhochschule des Mittelstands (FHM) - Campus Köln',
  'Fachhochschule des Mittelstands (FHM) - Campus Rostock',
  'Fachhochschule des Mittelstands (FHM) - Campus Schwerin',
  'Fachhochschule Dortmund',
  'Fachhochschule Dresden',
  'Fachhochschule Erfurt',
  'Fachhochschule für die Wirtschaft - Marburg',
  'Fachhochschule für die Wirtschaft - Mettmann',
  'Fachhochschule für die Wirtschaft Hannover',
  'Fachhochschule für Interkulturelle Theologie Hermannsburg',
  'Fachhochschule für Sport und Management Potsdam',
  'Fachhochschule Kiel',
  'Fachhochschule Kiel - Osterrönfeld',
  'Fachhochschule Lübeck',
  'Fachhochschule Münster',
  'Fachhochschule Potsdam',
  'Fachhochschule Schmalkalden',
  'Fachhochschule Stralsund',
  'Fachhochschule Südwestfalen - Standort Hagen',
  'Fachhochschule Südwestfalen - Standort Iserlohn',
  'Fachhochschule Südwestfalen - Standort Lüdenscheid',
  'Fachhochschule Südwestfalen - Standort Meschede',
  'Fachhochschule Südwestfalen - Standort Soest',
  'Fachhochschule Wedel',
  'Fachhochschule Westküste',
  'FernUniversität in Hagen',
  'FHM Tec Rheinland Institut für Technologie und Management',
  'Filmakademie Baden-Württemberg',
  'Filmuniversität Babelsberg Konrad Wolf',
  'Fliedner Fachhochschule Düsseldorf',
  'Folkwang Universität der Künste',
  'Folkwang Universität der Künste - Bochum',
  'Folkwang Universität der Künste - Dortmund',
  'Folkwang Universität der Künste - Duisburg',
  'FOM Fachhochschule für Ökonomie und Management',
  'FOM Hochschule für Oekonomie & Management',
  'FOM Hochschule für Oekonomie & Management - AGA Norddeutscher Unternehmensverband e.V.',
  'FOM Hochschule für Oekonomie & Management - B1st Software Factory',
  'FOM Hochschule für Oekonomie & Management - Berufsbildungszentrum Hammfeld',
  'FOM Hochschule für Oekonomie & Management - City Park Center',
  'FOM Hochschule für Oekonomie & Management - Germania Campus',
  'FOM Hochschule für Oekonomie & Management - Hans-Böckler-Berufskolleg',
  'FOM Hochschule für Oekonomie & Management - Hochschulzentrum Berlin',
  'FOM Hochschule für Oekonomie & Management - Hochschulzentrum Köln',
  'FOM Hochschule für Oekonomie & Management - Hochschulzentrum Mannheim',
  'FOM Hochschule für Oekonomie & Management - Hochschulzentrum Siegen',
  'FOM Hochschule für Oekonomie & Management - Hochschulzentrum Wesel',
  'FOM Hochschule für Oekonomie & Management - Hochschulzentrum Wuppertal',
  'FOM Hochschule für Oekonomie & Management - Neue Hopfenpost',
  'FOM Hochschule für Oekonomie & Management - Rheinwerk 3',
  'FOM Hochschule für Oekonomie & Management - Tec-Center',
  'FOM Hochschule für Oekonomie & Management - Technologiezentrum am Europaplatz Aachen',
  'FOM Hochschule für Oekonomie & Management - Technologiezentrum Ruhr',
  'FOM Hochschule für Oekonomie & Management - Unicom I – Technologiepark Universität Bremen',
  'Frankfurt School of Finance & Management',
  'Frankfurt School of Finance & Management Studienzentrum München',
  'Frankfurt University of Applied Sciences',
  'Freie Hochschule Stuttgart - Seminar für Waldorfpädagogik',
  'Freie Theologische Hochschule Gießen',
  'Freie Universität Berlin',
  'Friedrich-Alexander-Universität Erlangen-Nürnberg',
  'Friedrich-Schiller-Universität Jena',
  'Georg-August-Universität Göttingen',
  'German Graduate School of Management and Law gGmbH Heilbronn',
  'GISMA Business School, Berlin',
  'GISMA Business School, Hamburg',
  'GISMA Business School, Hannover',
  'GISMA Business School, Potsdam',
  'Globe Business College Munich',
  'Gottfried Wilhelm Leibniz Universität Hannover',
  'Gustav-Siewerth-Akademie',
  'HafenCity Universität Hamburg',
  'Hamburger Fern-Hochschule',
  'HAW Hamburg',
  'HAW Hof in Münchberg',
  'Heinrich-Heine-Universität Düsseldorf',
  'Helmut-Schmidt-Universität',
  'Hertie School of Governance',
  'Hessische Hochschule für Polizei und Verwaltung',
  'HHL Leipzig Graduate School of Management',
  'HMKW - Hochschule für Medien, Kommunikation und Wirtschaft',
  'HMKW - Hochschule für Medien, Kommunikation und Wirtschaft Campus Köln',
  'HMS Hamburg Media School',
  'Hochschulcampus Unna',
  'hochschule 21',
  'Hochschule Aalen - Technik und Wirtschaft Campus "Burren"',
  'Hochschule Albstadt-Sigmaringen',
  'Hochschule Anhalt',
  'Hochschule Anhalt - Dessau',
  'Hochschule Anhalt in Bernburg',
  'Hochschule Biberach - Hochschule für Architektur und Bauwesen, Betriebswirtschaft und Biotechnologie',
  'Hochschule Bochum',
  'Hochschule Bochum in Heiligenhaus',
  'Hochschule Bonn-Rhein-Sieg',
  'Hochschule Bonn-Rhein-Sieg - Campus Hennef',
  'Hochschule Bonn-Rhein-Sieg - Campus Rheinbach',
  'Hochschule Bremen',
  'Hochschule Bremerhaven',
  'Hochschule Darmstadt',
  'Hochschule der Bayerischen Wirtschaft für angewandte Wissenschaften',
  'Hochschule der Bayerischen Wirtschaft für angewandte Wissenschaften - Standort Traunstein',
  'Hochschule der bildenden Künste (HBK) Essen',
  'Hochschule der Bildenden Künste Saar',
  'Hochschule der Bundesagentur für Arbeit',
  'Hochschule der Bundesagentur für Arbeit - Campus Schwerin',
  'Hochschule der Deutschen Bundesbank',
  'Hochschule der Medien',
  'Hochschule der Sparkassen-Finanzgruppe',
  'Hochschule der Wirtschaft für Management',
  'Hochschule Düsseldorf',
  'Hochschule Emden/Leer',
  'Hochschule Esslingen',
  'Hochschule Esslingen - Flandernstraße',
  'Hochschule Esslingen - Stadtmitte',
  'Hochschule Flensburg',
  'Hochschule Fresenius',
  'Hochschule Fulda',
  'Hochschule Furtwangen - Informatik, Technik, Wirtschaft, Medien, Gesundheit',
  'Hochschule für angewandte Pädagogik',
  'Hochschule für Angewandte Sprachen/Fachhochschule des SDI',
  'Hochschule für angewandte Wissenschaft und Kunst',
  'Hochschule für angewandte Wissenschaft und Kunst, Fachhochschule Hildesheim/Holzminden/Göttingen',
  'Hochschule für angewandte Wissenschaften - Fachhochschule Ansbach',
  'Hochschule für angewandte Wissenschaften - Fachhochschule Aschaffenburg',
  'Hochschule für angewandte Wissenschaften - Fachhochschule Rosenheim',
  'Hochschule für angewandte Wissenschaften Augsburg',
  'Hochschule für angewandte Wissenschaften Coburg',
  'Hochschule für Angewandte Wissenschaften Hamburg',
  'Hochschule für Angewandte Wissenschaften Hof',
  'Hochschule für angewandte Wissenschaften Kempten',
  'Hochschule für angewandte Wissenschaften Landshut',
  'Hochschule für angewandte Wissenschaften München',
  'Hochschule für angewandte Wissenschaften Neu-Ulm',
  'Hochschule für angewandte Wissenschaften Würzburg-Schweinfurt',
  'Hochschule für angewandtes Management',
  'Hochschule für angewandtes Management in Ismaning',
  'Hochschule für angewandtes Management in Unna',
  'Hochschule für Bildende Künste Braunschweig',
  'Hochschule für Bildende Künste Dresden',
  'Hochschule für Bildende Künste Hamburg',
  'Hochschule für evangelische Kirchenmusik der Evangelisch-Lutherischen Kirche in Bayern',
  'Hochschule für Fernsehen und Film München',
  'Hochschule für Forstwirtschaft Rottenburg',
  'Hochschule für Gestaltung Offenbach am Main',
  'Hochschule für Gestaltung Schwäbisch Gmünd',
  'Hochschule für Gesundheit',
  'Hochschule für Grafik und Buchkunst Leipzig',
  'Hochschule für Internationales Management Heidelberg',
  'Hochschule für Jüdische Studien Heidelberg',
  'Hochschule für Katholische Kirchenmusik und Musikpädagogik',
  'Hochschule für Kirchenmusik der Diözese Rottenburg-Stuttgart',
  'Hochschule für Kirchenmusik der Evangelischen Kirche von Westfalen',
  'Hochschule für Kirchenmusik der Evangelischen Landeskirche in Baden',
  'Hochschule für Kirchenmusik der Evangelischen Landeskirche in Württemberg',
  'Hochschule für Kirchenmusik Dresden',
  'Hochschule für Kommunikation und Gestaltung',
  'Hochschule für Kommunikation und Gestaltung Ulm',
  'Hochschule für Kunst, Design und Populäre Musik Freiburg',
  'Hochschule für Kunsttherapie Nürtingen',
  'Hochschule für Künste Bremen',
  'Hochschule für Künste im Sozialen, Ottersberg',
  'Hochschule für Musik "Carl Maria von Weber" Dresden',
  'Hochschule für Musik "Hanns Eisler" Berlin',
  'Hochschule für Musik Detmold',
  'Hochschule für Musik Franz Liszt Weimar',
  'Hochschule für Musik Karlsruhe',
  'Hochschule für Musik Nürnberg',
  'Hochschule für Musik Saar',
  'Hochschule für Musik und Darstellende Kunst Frankfurt am Main',
  'Hochschule für Musik und Tanz Köln',
  'Hochschule für Musik und Tanz Köln in Aachen',
  'Hochschule für Musik und Tanz Köln in Wuppertal',
  'Hochschule für Musik und Theater "Felix Mendelssohn Bartholdy" Leipzig',
  'Hochschule für Musik und Theater Hamburg',
  'Hochschule für Musik und Theater München',
  'Hochschule für Musik und Theater Rostock',
  'Hochschule für Musik Würzburg',
  'Hochschule für Musik, Theater und Medien Hannover',
  'Hochschule für nachhaltige Entwicklung Eberswalde',
  'Hochschule für Philosophie',
  'Hochschule für Politik München',
  'Hochschule für Schauspielkunst "Ernst Busch"',
  'Hochschule für Technik Stuttgart',
  'Hochschule für Technik und Wirtschaft Berlin',
  'Hochschule für Technik und Wirtschaft des Saarlandes',
  'Hochschule für Technik und Wirtschaft Dresden',
  'Hochschule für Technik, Wirtschaft und Kultur Leipzig',
  'Hochschule für Technik, Wirtschaft und Medien Offenburg',
  'Hochschule für Telekommunikation Leipzig (FH)',
  'Hochschule für Wirtschaft und Recht Berlin Campus Lichtenberg',
  'Hochschule für Wirtschaft und Recht Berlin Campus Schöneberg',
  'Hochschule für Wirtschaft und Umwelt Nürtingen-Geislingen',
  'Hochschule für Wirtschaft, Technik und Kultur (HWTK)',
  'Hochschule für Wirtschaft, Technik und Kultur (HWTK) Studienort Baden-Baden',
  'Hochschule für Öffentliche Verwaltung Bremen',
  'Hochschule Geisenheim',
  'Hochschule Hamm-Lippstadt - Campus Hamm',
  'Hochschule Hamm-Lippstadt - Campus Lippstadt',
  'Hochschule Hannover',
  'Hochschule Harz, Hochschule für angewandte Wissenschaften',
  'Hochschule Harz, Hochschule für angewandte Wissenschaften (FH)',
  'Hochschule Heilbronn - Reinhold-Würth-Hochschule',
  'Hochschule Heilbronn Campus Schwäbisch Hall',
  'Hochschule Heilbronn, Technik, Wirtschaft, Informatik',
  'Hochschule Kaiserslautern',
  'Hochschule Karlsruhe Technik und Wirtschaft',
  'Hochschule Koblenz',
  'Hochschule Koblenz in Höhr-Grenzhausen',
  'Hochschule Koblenz in Remagen',
  'Hochschule Konstanz Technik, Wirtschaft und Gestaltung',
  'Hochschule Ludwigshafen am Rhein',
  'Hochschule Macromedia',
  'Hochschule Magdeburg-Stendal',
  'Hochschule Mainz',
  'Hochschule Mannheim',
  'Hochschule Merseburg',
  'Hochschule Mittweida',
  'Hochschule Neubrandenburg',
  'Hochschule Neuss für Internationale Wirtschaft',
  'Hochschule Niederrhein',
  'Hochschule Niederrhein - Campus Mönchengladbach',
  'Hochschule Nordhausen',
  'Hochschule Offenburg - Campus Gengenbach',
  'Hochschule Osnabrück',
  'Hochschule Osnabrück in Lingen',
  'Hochschule Ostwestfalen-Lippe - Studienzentrum Warburg',
  'Hochschule Pforzheim - Gestaltung, Technik, Wirtschaft und Recht',
  'Hochschule Ravensburg-Weingarten',
  'Hochschule Reutlingen',
  'Hochschule Reutlingen in Böblingen',
  'Hochschule Rhein-Waal',
  'Hochschule Rhein-Waal',
  'Hochschule RheinMain',
  'Hochschule Rosenheim in Burghausen',
  'Hochschule Rosenheim in Mühldorf a. Inn',
  'Hochschule Ruhr West',
  'Hochschule Trier',
  'Hochschule Trier - Umwelt-Campus Birkenfeld',
  'Hochschule Trier in Idar-Oberstein - Fachrichtung Edelstein und Schmuck',
  'Hochschule Ulm Technik, Informatik und Medien',
  'Hochschule Weihenstephan-Triesdorf',
  'Hochschule Weserbergland',
  'Hochschule Wismar',
  'Hochschule Wismar - Außenstelle Malchow',
  'Hochschule Wismar - Außenstelle Rostock-Warnemünde',
  'Hochschule Worms',
  'Hochschule Zittau/Görlitz',
  'HS Kaiserslautern - Studienort Pirmasens',
  'HS Kaiserslautern - Studienort Zweibrücken',
  'HSBA Hamburg School of Business Administration',
  'HSD Hochschule Döpfer',
  'Humboldt-Universität zu Berlin',
  'IB Hochschule',
  'IB Hochschule Berlin Studienzentrum Coburg',
  'IB Hochschule Berlin Studienzentrum Hamburg',
  'IB Hochschule Berlin Studienzentrum Köln',
  'IB Hochschule Berlin Studienzentrum Stuttgart',
  'ICN Business School',
  'ifs internationale filmschule',
  'igv Köln',
  'International Psychoanalytic University Berlin',
  'International School of Management',
  'Internationale Berufsakademie',
  'Internationale Berufsakademie Studienort Bochum',
  'Internationale Berufsakademie Studienort Erfurt',
  'Internationale Berufsakademie Studienort Freiburg',
  'Internationale Berufsakademie Studienort Hamburg',
  'Internationale Berufsakademie Studienort Heidelberg',
  'Internationale Berufsakademie Studienort Kassel',
  'Internationale Berufsakademie Studienort Köln',
  'Internationale Berufsakademie Studienort Leipzig',
  'Internationale Berufsakademie Studienort München',
  'Internationale Berufsakademie Studienort Nürnberg',
  'Internationale Hochschule Liebenzell (IHL)',
  'IST-Hochschule für Management',
  'IUBH Duales Studium',
  'Jacobs University Bremen',
  'Jade Hochschule - Wilhelmshaven/Oldenburg/Elsfleth',
  'Jade Hochschule Wilhelmshaven/Oldenburg/Elsfleth',
  'Johann Wolfgang Goethe-Universität Frankfurt am Main',
  'Johannes Gutenberg-Universität Mainz',
  'Johannes Gutenberg-Universität Mainz - Campus Germersheim',
  'Julius-Maximilians-Universität Würzburg',
  'Justus-Liebig-Universität Gießen',
  'Karlshochschule International University',
  'Karlsruhe University of Applied Sciences',
  'Karlsruher Institut für Technologie',
  'Katholische Hochschule Freiburg',
  'Katholische Hochschule für Sozialwesen Berlin',
  'Katholische Hochschule Mainz',
  'Katholische Hochschule Nordrhein-Westfalen',
  'Katholische Stiftungsfachhochschule München',
  'Katholische Universität Eichstätt',
  'Kirchliche Hochschule Wuppertal/Bethel',
  'Kirchliche Hochschule Wuppertal/Bethel - Bielefeld',
  'Kommunale Hochschule für Verwaltung in Niedersachsen',
  'Kunstakademie Düsseldorf',
  'Kunstakademie Münster Hochschule für Bildende Künste',
  'Kunsthochschule für Medien Köln',
  'Kunsthochschule Kassel',
  'Kühne Logistics University',
  'Leibniz-Fachhochschule',
  'Leipzig School of Media',
  'Leuphana Universität Lüneburg',
  'LMU Ludwig-Maximilians-Universität München - Tierärztliche Fakultät',
  'LMU Ludwig-Maximilians-Universität München Martinsried Biochemie',
  'Ludwig-Maximilians-Universität München',
  'Lutherische Theologische Hochschule Oberursel',
  'Martin-Luther-Universität Halle-Wittenberg',
  'MD.H Mediadesign Hochschule',
  'media Akademie - Hochschule Stuttgart',
  'Mediadesign Hochschule für Design und Informatik',
  'Mediencampus der Hochschule Darmstadt',
  'Medizinische Fakultät Mannheim der Universität Heidelberg',
  'Medizinische Hochschule Brandenburg Theodor Fontane',
  'Medizinische Hochschule Brandenburg Theodor Fontane - Brandenburg an der Havel',
  'Medizinische Hochschule Hannover (MHH)',
  'Merz Akademie Hochschule für Gestaltung, Kunst und Medien, Stuttgart',
  'MSB Medical School Berlin',
  'MSH Medical School Hamburg',
  'Munich Business School',
  'Musikakademie der Stadt Kassel „Louis Spohr“',
  'Musikhochschule Lübeck',
  'Muthesius Kunsthochschule',
  'Naturwissenschaftlich-Technische Akademie Prof. Dr. Grübler gGmbH',
  'NBS Northern Business School - Hochschule für Management und Sicherheit',
  'New European College',
  'Nordakademie',
  'Nordakademie - Hamburg',
  'Ostbayerische Technische Hochschule Amberg-Weide',
  'Ostbayerische Technische Hochschule Regensburg',
  'Ostbayrische Technische Hochschule Amberg-Weiden',
  'Ostfalia Hochschule für angewandte Wissenschaften',
  'Otto-Friedrich-Universität Bamberg',
  'Otto-von-Guericke-Universität Magdeburg',
  'Palucca Hochschule für Tanz Dresden',
  'Paracelsus Medizinische Privatuniversität',
  'PFH - Private Hochschule Göttingen',
  'Philipps-Universität Marburg',
  'Philosophisch-Theologische Hochschule Münster',
  'Philosophisch-Theologische Hochschule Sankt Georgen Frankfurt am Main',
  'Philosophisch-Theologische Hochschule SVD Sankt Augustin',
  'Philosophisch-Theologische Hochschule Vallendar der Gesellschaft des Katholischen Apostolates (Pallottiner)',
  'Popakademie Baden-Württemberg GmbH',
  'Praxishochschule Standort Rheine',
  'Private Hochschule für Wirtschaft und Technik',
  'Private Hochschule für Wirtschaft und Technik Vechta/Diepholz/Oldenburg',
  'Private Hochschule Göttingen - Hansecampus Stade',
  'Private Universität Witten/Herdecke gGmbH',
  'Provadis School of International Management and Technology',
  'Psychologische Hochschule Berlin',
  'Pädagogische Hochschule Freiburg',
  'Pädagogische Hochschule Heidelberg',
  'Pädagogische Hochschule Karlsruhe',
  'Pädagogische Hochschule Ludwigsburg',
  'Pädagogische Hochschule Schwäbisch Gmünd',
  'Pädagogische Hochschule Weingarten',
  'Quadriga Hochschule Berlin',
  'Rheinisch-Westfälische Technische Hochschule Aachen',
  'Rheinische Fachhochschule Köln',
  'Rheinische Fachhochschule Köln in Wermelskirchen',
  'Rheinische Friedrich-Wilhelms-Universität Bonn',
  'Robert-Schumann-Hochschule Düsseldorf',
  'Ruhr-Universität Bochum',
  'Ruprecht-Karls-Universität Heidelberg',
  'SAE Institute Berlin',
  'SAE Institute Bochum',
  'SAE Institute Frankfurt',
  'SAE Institute Hamburg',
  'SAE Institute Hannover',
  'SAE Institute Köln',
  'SAE Institute Leipzig',
  'SAE Institute München',
  'SAE Institute Stuttgart',
  'Schiller International University – Campus Heidelberg',
  'Sigmund Freud PrivatUniversität Berlin',
  'SRH Fachhochschule für Gesundheit Gera',
  'SRH Fachhochschule für Gesundheit Gera gGmbH - Bonn',
  'SRH Fachhochschule für Gesundheit Gera gGmbH - Leverkusen',
  'SRH Fernhochschule Riedlingen',
  'SRH Hochschule - Studienzentrum Dresden',
  'SRH Hochschule - Studienzentrum Düsseldorf',
  'SRH Hochschule Berlin',
  'SRH Hochschule der populären Künste GmbH',
  'SRH Hochschule für Logistik und Wirtschaft',
  'SRH Hochschule für Wirtschaft und Medien Calw',
  'SRH Hochschule Heidelberg',
  'Staatliche Akademie der Bildenden Künste Karlsruhe',
  'Staatliche Akademie der Bildenden Künste Stuttgart',
  'Staatliche Hochschule für Bildende Künste (Städelschule) Frankfurt am Main',
  'Staatliche Hochschule für Gestaltung Karlsruhe',
  'Staatliche Hochschule für Musik Freiburg im Breisgau',
  'Staatliche Hochschule für Musik Trossingen',
  'Staatliche Hochschule für Musik und Darstellende Kunst Mannheim',
  'Staatliche Hochschule für Musik und Darstellende Kunst Stuttgart',
  'Steinbeis-Hochschule-Berlin',
  'Stiftung Tierärztliche Hochschule Hannover',
  'Technische Akademie Esslingen - Studienzentrum Ostfildern',
  'Technische Fachhochschule Georg Agricola für Rohstoff, Energie und Umwelt zu Bochum',
  'Technische Hochschule Bingen',
  'Technische Hochschule Brandenburg',
  'Technische Hochschule Deggendorf',
  'Technische Hochschule Ingolstadt',
  'Technische Hochschule Köln',
  'Technische Hochschule Köln - Campus Gummersbach',
  'Technische Hochschule Köln - Campus Leverkusen',
  'Technische Hochschule Mittelhessen',
  'Technische Hochschule Nürnberg Georg Simon Ohm',
  'Technische Hochschule Ostwestfalen-Lippe - Standort Detmold',
  'Technische Hochschule Ostwestfalen-Lippe - Standort Höxter',
  'Technische Hochschule Ostwestfalen-Lippe - Standort Lemgo',
  'Technische Hochschule Wildau (FH)',
  'Technische Universität Bergakademie Freiberg',
  'Technische Universität Berlin',
  'Technische Universität Carolo-Wilhelmina zu Braunschweig',
  'Technische Universität Chemnitz',
  'Technische Universität Clausthal',
  'Technische Universität Darmstadt',
  'Technische Universität Dortmund',
  'Technische Universität Dresden',
  'Technische Universität Hamburg',
  'Technische Universität Ilmenau',
  'Technische Universität Kaiserslautern',
  'Technische Universität München',
  'Technische Universität München - Campus Weihenstephan',
  'Technische Universität München in Garching',
  'Theologische Fakultät Fulda',
  'Theologische Fakultät Paderborn',
  'Theologische Fakultät Trier',
  'Theologische Hochschule Elstal',
  'Theologische Hochschule Friedensau',
  'Theologische Hochschule Reutlingen',
  'Theologisches Seminar Ewersbach',
  'Touro College Berlin',
  'TU Dresden - IHI Zittau',
  'UE (University of Applied Sciences Europe)',
  'Ukrainische freie Universität',
  'UNIKIMS - Die Managementschool der Universität Kassel',
  'University of Applied Sciences Würzburg-Schweinfurt',
  'University of Konstanz',
  'Universität Augsburg',
  'Universität Bayreuth',
  'Universität Bielefeld',
  'Universität Bremen',
  'Universität der Bundeswehr München',
  'Universität der Künste Berlin',
  'Universität des Saarlandes',
  'Universität des Saarlandes - Homburg',
  'Universität Duisburg-Essen',
  'Universität Erfurt',
  'Universität Hamburg',
  'Universität Hildesheim',
  'Universität Hohenheim',
  'Universität Kassel',
  'Universität Koblenz-Landau - Campus Koblenz',
  'Universität Koblenz-Landau - Campus Landau',
  'Universität Konstanz',
  'Universität Leipzig',
  'Universität Mannheim',
  'Universität Osnabrück',
  'Universität Paderborn',
  'Universität Passau',
  'Universität Potsdam',
  'Universität Regensburg',
  'Universität Rostock',
  'Universität Siegen',
  'Universität Stuttgart',
  'Universität Trier',
  'Universität Ulm',
  'Universität Vechta',
  'Universität zu Köln',
  'Universität zu Lübeck',
  'VWA-Hochschule für berufsbegleitendes Studium Stuttgart',
  'VWA-Hochschule für berufsbegleitendes Studium Stuttgart Campus Freiburg',
  'weißensee kunsthochschule berlin',
  'Westfälische Hochschule',
  'Westfälische Hochschule - Standort Ahaus',
  'Westfälische Hochschule - Standort Bocholt',
  'Westfälische Hochschule - Standort Recklinghausen',
  'Westfälische Wilhelms-Universität Münster',
  'Westsächsische Hochschule Zwickau',
  'Westsächsische Hochschule Zwickau - Markneukirchen',
  'Westsächsische Hochschule Zwickau - Reichenbach',
  'Westsächsische Hochschule Zwickau - Schneeberg',
  'WFI - Ingolstadt School of Management',
  'WHU - Otto Beisheim School of Management',
  'Wilhelm Büchner Hochschule',
  'Wilhelm Löhe Hochschule für angewandte Wissenschaften',
  'Zeppelin Universität - Hochschule zwischen Wirtschaft, Kultur und Politik',
];
